### ISSUE TITLE
Some args ignored when put in nodemon.json

### ISSUE THREAD

**Issue by SeanHayes** [remy/nodemon#1009]
This works:
`nodemon --trace-warnings build/app.js
`

but putting
`  "trace-warnings": true,
`

in my nodemon.json and running 
`nodemon build/app.js
`

ignores `trace-warnings`.

**Comment by royscale** [comment]
I think this may be because node only seems to pay attention to `--trace-warnings` if it comes before the file name, so while running `node --trace-warnings build/app.js` will trace warnings, `node build/app.js --trace-warnings`will not actually trace warnings and since nodemon appears to just pass on arguments to node, if `--trace-warnings` comes after the file name in the nodemon command, the node process spawned will not honor the `--trace-warnings` flag since it comes after the filename.  This leads me to believe that `nodemon` with `"trace-warnings": true,` in the config file does not trace warnings because when node turns `"trace-warnings": true,` into an argument to pass on to node, it puts `--trace-warnings` after the filename leading node to ignore it.

Does that sound plausible to you?
