### ISSUE TITLE
How to watch only root files?

### ISSUE THREAD

**Issue by kud** [remy/nodemon#1023]
I would like to watch only root files by watching "." without subdirectories. Is it possible?

**Comment by kud** [comment]
Because for the moment, it's not so dev-friendly:

```js
{
  "verbose": false,
  "watch": [
      ".",
      ".babelrc",
      ".eslintrc.js"
  ],
  "ignore": [
    "node_modules",
    "dist",
    "src",
    "__mocks__",
    "__tests",
    "*.md",
    "*.txt",
    "*.py",
    "*.pyc"
  ]
}
```

**Comment by kud** [comment]
:)

**Comment by remy** [comment]
I've just been investigating this, and it's kinda of a weird case to only monitor one depth deep, but I can't see any way to do it so far…and I've tried a lot of combinations on the watch/ignore settings.

I'm happy to reopen this if there's demand for it (+1s, etc). Otherwise, I think the non-dev friendly way is the only way.
