### ISSUE TITLE
How can I watch multiple directories?

### ISSUE THREAD

**Issue by vforv** [remy/nodemon#1076]
I need something like this:

```
[{
  "watch": ["src/api-gateway"],
  "ext": "ts",
  "ignore": ["src/**/*.spec.ts"],
  "exec": "ts-node ./src/api-gateway/main.ts"
},
{
  "watch": ["src/services/ping-service"],
  "ext": "ts",
  "ignore": ["src/**/*.spec.ts"],
  "exec": "ts-node ./src/services/ping-service/ping-service.ts"  
}]
```

Is that possible?

**Comment by nsoseka** [comment]
I think if you run nodemon from from a parent directory where you have your file that starts the server it watches changes to all the files in sub directories.
or you could try watch: "src/.". Not really sure though.

**Comment by ouqinglai** [comment]
@vforv deal with it？

**Comment by rhernandog** [comment]
Hello,

Sorry to bring this back, but I'm having some issues with specific watched directories in an express app.

From the docs I have this:

```nodemon --watch app --watch libs app/server.js```

When I try to run this code nothing happens when something changes in any of the directories being watched:

```nodemon --watch build --watch public build/server.js```

Basically I want to restart the server whenever there's a change in the server or client code. The server does start but never restarts automatically when a change happens and the bundling process is working fine.

If I run the code without the `watch` flags, nodemon looks for changes in all the folders and it does works. What I want is to keep track only of those two folders.

**Comment by nsoseka** [comment]
@rhernandog have you tried out all the solutions above?

**Comment by remy** [comment]
@rhernandog can you give this a test with latest nodemon@1.13.3? I think I found this in the code and fixed it (not sure how it broke, but I was able to replicate the issue with a single dir and then this latest build fixes it).

**Comment by rhernandog** [comment]
@remy Thanks I'll update the package and let you know how it went.

**Comment by remy** [comment]
@rhernandog can you test with nodemon@1.14.0? I've pushed a change that fixes (some) directory watching problems.

**Comment by remy** [comment]
This is working in the latest release. Please go ahead and upgrade ❤️

**Comment by rhernandog** [comment]
@remy Sorry I couldn't get back before.

Is working great with the latest update, thanks for the great work!!! :clap::clap:
