### ISSUE TITLE
Express with Nodemon

### ISSUE THREAD

**Issue by arthurchui** [remy/nodemon#110]
**Any idea with the following exception?**

---

> nodemon app.js 

3 Jul 17:56:55 - [nodemon] v0.6.22
3 Jul 17:56:55 - [nodemon] watching: /home/arthur/Projects/node/carlo
3 Jul 17:56:55 - [nodemon] starting `node app.js`
3 Jul 17:56:55 - [nodemon] starting `node app.js`
Express server listening on port 3000

events.js:66
        throw arguments[1]; // Unhandled 'error' event
                       ^
Error: listen EADDRINUSE
    at errnoException (net.js:781:11)
    at Server._listen2._connectionKey (net.js:922:26)
    at process.startup.processNextTick.process._tickCallback (node.js:244:9)
3 Jul 17:56:55 - [nodemon] app crashed - waiting for file changes before starting...

**Comment by kesteinbakk** [comment]
I know this is old and closed, but... I'm running nodemon v1.3.7 on windows 7 64bits with node 0.12.2. When running node normally there is no problem, but when I use nodemon it starts two node.exe processes. Auto-restarting due to changes in scripts is no problem, but if I exit nodemon (ctr+c), only one of the node.exe processes is terminated. Re-staring nodemon (without terminating the other node.exe process manually from task-manager), leads to a "port xxx is already in use" msg and "app crashed" error from nodemon. Expected?

**Comment by cozuya** [comment]
@kesteinbakk I'm having the same issue, but while using the gulp task runner's nodemon extension.  Both OSX and windows 7 are seeing the same behavior.
