### ISSUE TITLE
Paths with @ in the name are not watched

### ISSUE THREAD

**Issue by gerhardcit** [remy/nodemon#1157]
- `nodemon -v`: 1.12.5
- `node -v`: 6.11.2
- Command you ran:
cd /Users/me/projects/dev/node_modules/@mymods/app1
nodemon --verbose index.js

### Expected behaviour
[nodemon] watching 1 files

### Actual behaviour
[nodemon] watching 0 files

### Steps to reproduce
put your app in a path with @ in the name

---
we use that often to develop modules like this: @ournpm/npm-module1.  The are consumed by a upstream project
 /Users/me/projects/dev/consumer-app which would find the node_module without having to install it.

**Comment by remy** [comment]
Related (I believe) to #916

**Comment by dominykas** [comment]
I believe the `@` in the path is unrelated - the clue is in `cd /Users/me/projects/dev/node_modules/` - `node_modules` is ignored by default and so the whole path gets ignored, so yes - I'd say this is the same issue as #916.

**Comment by dominykas** [comment]
Verified by [overriding ignored folders](https://github.com/remy/nodemon/blob/master/faq.md#overriding-the-underlying-default-ignore-rules) - the `@` has no effect, but `node_modules` does.

@gerhardcit can you please confirm if `nodemon` watches things correctly when the folder with an `@` in the name is in a path which does not contain `node_modules`, while the fix is being worked on?

**Comment by remy** [comment]
Pretty sure #1186 when deployed will fix this particular issue.

**Comment by remy** [comment]
Live in nodemon latest.
