### ISSUE TITLE
Crash On Folder Delete

### ISSUE THREAD

**Issue by atom0s** [remy/nodemon#1213]
- `nodemon -v`: 1.14.8
- `node -v`: 8.9.4
- Operating system/terminal environment: Windows 10 / PowerShell
- Command you ran:

nodemon --verbose

### Expected behaviour

When the folder is deleted, a filter match attempt should be made and a refresh triggered if not ignored.

### Actual behaviour

nodemon crashes with an internal error message.

### Steps to reproduce

1. Create a folder named anything within the parent folder (or any sub folder). (ie. etc)
2. Start nodemon within the parent folder.
3. Delete the created folder.

Nodemon will crash reporting:

```
[nodemon] Internal watch failed: Error watching file for changes: EPERM
[nodemon] exiting
```

This is with Powershell ran as administrator.

**Comment by remy** [comment]
Looks to be windows specific, certainly on first test on Mac. Ran nodemon with a directory foo, removed dir, nodemon still working.

@atom0s in the meantime, can you test on your end with `npm install nodemon@debug`? It's got a couple of subtle changes to the way folders are watched and might make a difference.

**Comment by atom0s** [comment]
Removed old nodemon via:
```npm uninstall -g nodemon```

Installed debug with:
```npm install -g nodemon@debug```

Ran with:
```nodemon --verbose```

Deleted a folder and still crashed with the same error.

**Comment by atom0s** [comment]
Jumped onto my desktop (Windows 8.1) and tested this as well with debug nodemon. Same crash so doesn't look to be Win 10 specific.

**Comment by remy** [comment]
I can't replicate this on Windows at all.

![2018-01-07](https://user-images.githubusercontent.com/13700/34653821-ad286e04-f3e9-11e7-8833-666183af7c41.png)

I couldn't work out how to run a screencast in Windows, but the above is a screenshot of two PS terminals running. On the left, I've tweaked nodemon so that the files being watched are echo'ed out. On the right, I delete the `foo` directory, and nodemon picks up the change, but doesn't bail (it shows a list of files before the change.

When I trigger a restart via a VS Code change, nodemon correctly restarts (and lists the files it's watching, now sans the foo directory).

There's a change I can make that might mitigate this, but I'm not quite sure what I'm missing that means I can't replicate. Perhaps you can share a screencast?

**Comment by atom0s** [comment]
Sorry for the delayed response. Newest version pushed fixed this for me. Thanks. :)
