### ISSUE TITLE
404 Error Unable to install

### ISSUE THREAD

**Issue by Laycoonz** [remy/nodemon#1222]
- `nodemon -v`:
- `node -v`:
- Operating system/terminal environment:  Windows 10
- Command you ran: npm install --save-dev nodemon

### Expected behaviour
Successful installation

### Actual behaviour
404 Not Found: duplexer3@https://registry.npmjs.org/duplexer3/-/duplexer3-0.1.5.tgz

### Steps to reproduce
Install node.
Install nodemon as a development dependency

---

If applicable, please append the `--dump` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens**.

**Comment by remy** [comment]
You're hitting some kind of cached entry - either for your package or npm somehow. This is related to the [outage they had recently](https://blog.npmjs.org/post/169432444640/npm-operational-incident-6-jan-2018). Specifically, 0.1.5 of Duplexer3 doesn't exist: https://registry.npmjs.org/duplexer3/latest.

I'd recommend running `npm cache clean` and retrying, otherwise raising with the npm people (like I said, it's directly related to their outage and their CDN caching a bad/wrong package).
