### ISSUE TITLE
[question] is it possible to setup nodemon to execute multiple commands watching multiple corresponding file sources?

### ISSUE THREAD

**Issue by zhenyulin** [remy/nodemon#1239]
was trying to achieve something similar by `npm-scripts-watcher` with nodemon
https://github.com/wehkamp/npm-scripts-watcher

**Comment by remy** [comment]
You can use `--exec "foo & bar & car"` to execute multiple commands from nodemon (though, this might not be compatible with Windows, you'll have to investigate yourself).

Other than using that method: no.

**Comment by mzalazar** [comment]
This worked for me:
..
`"start": "nodemon --exec 'clear && babel-node' src/app.js"`
...

(in package.json)

**Comment by danielo515** [comment]
If I do the `&&` trick the spawned server is not reachable. Any idea why?

**Comment by mzalazar** [comment]
That's weird... because it's a linux common "pattern", you can try it from a linux terminal:

`nodemon --exec 'clear && babel-node' src/app.js`

and check for errors in the console... if that's not working for you, execute your script without nodemon:
`babel-node src/app.js`

and test your app.

**Comment by danielo515** [comment]
I can run it without nodemon without problems, so it has something with nodemon for sure. Maybe it is because I'm just running another npm command, not sure. 
Basically what I have is:

```js
build: "build pipeline here",
start: "run the server here",
watch: "nodemon --exec 'npm run build && npm run start'"
```

Which works as expected an I even see the running server on the console, but then I can not reach it. Maybe nodemon creating several children can have this effect ?

I'm quite surprised with what you proposed. Does that mean that I can pass any argument to the app?

Regards

**Comment by Jleagle** [comment]
> You can use `--exec "foo & bar & car"` to execute multiple commands from nodemon (though, this might not be compatible with Windows, you'll have to investigate yourself).
> 
> Other than using that method: no.

This is not compatible with long running processes

**Comment by Olliebrown** [comment]
I know things are getting a little stale here but wanted to offer up the solution I found.  In general, fancy bash/*nix shell commands have caused issues for me as they don't run universally (usually cause problems for users on Windows, where the shell is, well, uncertain).  The '&' and '&&' commands are a good example of this.  To get around this, I've started using different 'npm' packages that offer universal alternatives.

One example is [rimraf ](https://www.npmjs.com/package/rimraf) which provides a universal command to remove an entire directory (`rm -rf` on *nix shells).

The most relevant one to this question is [npm-run-all](https://www.npmjs.com/package/npm-run-all):
- This provides a way you can queue up several 'scripts' from your package.json to run, either in parallel or in sequence
- `run-s` is provided by this package and executes the listed scripts sequentially
- Here's a setup that builds with 'esbuild' before running with node, all monitored with nodemon:
```JSON
  "scripts": {
    "dev": "nodemon --exec npm run devbuild",
    "build": "run-s clean build-bot",
    "clean": "rimraf dist",

    "devbuild": "run-s clean devbuild-bot devstart",
    "devbuild-bot": "esbuild --platform=node --bundle --outfile=dist/scrummybot.js index.js",

    "build-bot": "esbuild --platform=node --bundle --minify --outfile=dist/scrummybot.min.js index.js",

    "devstart": "node dist/scrummybot.js",
    "start": "node dist/scrummybot.min.js"
  },
```

The dev command starts up nodemon and nodemon just runs another package.json script ('devbuild').  Devbuild will trigger a clean, then a build, and finally starts the program.  When nodemon detects a change, it kills this original process and restarts it.  Works pretty well for me when I have things that need to be built first (usually because they are using ES Next type features that node doesn't support).

**Comment by yucongo** [comment]
`"start": "nodemon --exec 'clear && babel-node' src/app.js"` single quotes do not work in Windows. Double quotes do (need to escape " inside)
```bash
`"start": "nodemon --exec \"clear && babel-node\" src/app.js"`
```

**Comment by davidmroth** [comment]
Heres is what I ended up with that's working realtively well:

```
"develop": "npm i nodemon; nodemon --exec \"npx prettier --write '{,./src/}{,*/**/}*.{js,json}'\" && node src/server.js",
```

**Comment by santimirandarp** [comment]
This set up was quite useful to me, running eslint and prettier in typescript (may add the tests also):
```
 "scripts": {
       "compile": "tsc -b",
       "eslint": "eslint src/**/*.ts --cache",
       "prettierw": "prettier src/**/*.ts --write",
       "dev": "nodemon -e ts --watch src/ --exec 'npm run eslint && npm run prettierw' "
    },
```

Good to emphasize that `-e ts` is necessary as that's not watched by default.

**Comment by iradofurioso** [comment]
> `"start": "nodemon --exec 'clear && babel-node' src/app.js"` single quotes do not work in Windows. Double quotes do (need to escape " inside)
> 
> ```shell
> `"start": "nodemon --exec \"clear && babel-node\" src/app.js"`
> ```

Thanks, it did work for me. I want to make my api compatible to all environments and that double quotes scaped did the trick.
