### ISSUE TITLE
[question]is there any reasons for unix globbing not supported in nodemon

### ISSUE THREAD

**Issue by jasonxia23** [remy/nodemon#1240]
> Don't use unix globbing to pass multiple directories, e.g --watch ./lib/*, it won't work. You need a --watch flag per directory watched.

IMO, supporting unix globbing would make config clearer.  
Is there any other reasons for unix globbing not supported in nodemon.

**Comment by remy** [comment]
It's because the `watch` argument requires a string that represents a glob, otherwise if you use the shell glob, the result is multiple filenames after the `watch` option and nodemon doesn't know when to stop reading the file arguments and when it's hit the actual executable file (since it will look the same on the command line).

**Comment by Zakini** [comment]
But if the patterns were quoted, you could use something like node-glob to parse the pattern yourself. It might not be quite the same but it should give roughly the same functionality.

**Comment by remy** [comment]
Patterns are supported once they're quoted.

**Comment by Zakini** [comment]
In that case, it's not at all clear that they're supported from the docs, but I guess that should be a separate issue.

**Comment by dmk255** [comment]
I've been having trouble using globs even with quotes - I would love for the docs to be updated

**Comment by remy** [comment]
@dmk255 a pull request will get you further than love. True code fact.
