### ISSUE TITLE
Consider using the opencollective CLI to show donation banner

### ISSUE THREAD

**Issue by Janpot** [remy/nodemon#1244]
In an effort to add constructive follow-up to #1189.

Would you consider replacing the banner with one that is generated by the [opencollective-cli](https://github.com/opencollective/opencollective-cli)?
First of all this would make it look prettier.
Second, if there is a future effort by the opencollective team to hide the banner when you're already a donor, it would automatically apply to this package. 
Third, it would move the discussion of showing/hiding the banner to the opencollective repo, where it belongs.

**Comment by remy** [comment]
Just on your points:

1. That's a subjective quality. I think (subjective) that the opencollective version is larger and more intrusive.
2. _if_ being operative, by the looks of the upcoming features, the focus is on a lot more interface that I wouldn't need embedded inside of nodemon. (I also try to keep my nested deps down where I can).
3. It doesn't move the conversation at all, sadly, because the messages will be directed here by those who would rather not be reminded they use software for free. 

Thanks all the same, but I think the best plan…ne, only plan is the one I suggested when locking that issue.

**Comment by Janpot** [comment]
@remy makes sense, though

1. If it were dismissible by donating, would be all the more incentive to actually make a donation.
2. It could be an optional dependency and fallback to the current behavior
3. One could argue that you're not using it for free after you donated. But I understand opinions differ on that. The thing is that right now, the discussions are already directed to this repo, with no other option than just shutting them down. plus, a global solution could benefit other opencollective projects.

That being said, this is not a plea for reopening this ticket. I can't make time for implementing this, neither would I benefit from doing so.

**Comment by Janpot** [comment]
Relevant discussion on OC CLI repo: https://github.com/opencollective/opencollective-cli/issues/7
