### ISSUE TITLE
Path resolution broken on Windows with 1.14.12

### ISSUE THREAD

**Issue by daguej** [remy/nodemon#1251]
- `nodemon -v`: 1.14.12
- `node -v`: 8.4.0
- Operating system/terminal environment: Windows 10

This breaks with the most recent version of nodemon:

    > nodemon --watch server --exec node_modules/.bin/ts-node -- server/dev.ts
    [nodemon] 1.14.12
    [nodemon] to restart at any time, enter `rs`
    [nodemon] watching: D:\project\path\server/**/*
    [nodemon] starting `node_modules/.bin/ts-node server/dev.ts`
    'node_modules' is not recognized as an internal or external command, operable program or batch file.
    [nodemon] app crashed - waiting for file changes before starting...

If I `npm install nodemon@1.14.11`:

    > nodemon --watch server --exec node_modules/.bin/ts-node -- server/dev.ts
    [nodemon] 1.14.11
    [nodemon] to restart at any time, enter `rs`
    [nodemon] watching: D:\project\path\server/**/*
    [nodemon] starting `node_modules/.bin/ts-node server/dev.ts`
    dev server listening!

Looks like the forward slashes `/` are not getting converted to `\` on Windows.

**Comment by remy** [comment]
I can see what change is causing this, but I wanted to ask a couple of questions to get a bit more context:

1. How do you run `ts-node` without nodemon? Specifically: what is the command you use to get your dev server listening.
2. What terminal in Windows were you using? Command Prompt, Powershell, gitbash, etc…
3. What happens when you run `nodemon --watch server --exec node_modules\.bin\ts-node -- server\dev.ts`

**Comment by andrewburgess** [comment]
I'm running into this issue as well. Converting the path separators from `/` to `\\` in the `exec` parameter seems to fix the issue.

My original run script was:

`nodemon -e ts,graphql --exec \"./node_modules/.bin/ts-node --inspect=0.0.0.0:9229 --type-check packages/server/index.ts | ./node_modules/.bin/bunyan\"`

which is now failing to start

Changing the path separators to Windows ones so that it works looks like:

`nodemon -e ts,graphql --exec \".\\node_modules\\.bin\\ts-node --inspect=0.0.0.0:9229 --type-check packages/server/index.ts | .\\node_modules\\.bin\\bunyan\"`

**Comment by daguej** [comment]
1. Don't really run without nodemon.  Our dev server is started using `npm start`; the `start` script in package.json is `nodemon --watch server --exec node_modules/.bin/ts-node -- server/dev.ts`.
2. cmd.exe (ConEmu)
3. It works.

Can't really change the path separators in the `start` script since that would presumably break it for my *nix colleagues.

**Comment by andrewburgess** [comment]
@daguej agreed, I was just pointing out that something changed between `1.14.11` and `1.14.12` with regards to path separator handling, and changing them can be a quick fix to prevent being stuck.

I switch between Mac and Windows often, so it's only a temporary solution for me as well

**Comment by remy** [comment]
For reference (I suspect my own) this was the commit that caused this particular issue: https://github.com/remy/nodemon/commit/33fa6f4970412a6bfa12ff357f44dfebf0ad63c7

**Comment by remy** [comment]
Better/simpler example on how to replicate from issue #1269 here:

```
nodemon -C --watch broken\touchme.txt --exec "echo changed"
```

On cmd / Windows 10 via @brkc

**Comment by remy** [comment]
[deleting my previous comment as it was incorrect]
