### ISSUE TITLE
Should nodemon pass `--inspect` (et al) to node automatically?

### ISSUE THREAD

**Issue by eilgin** [remy/nodemon#1263]
- `nodemon -v`: 1.15.1
- `node -v`: 8.9.4
- Operating system/terminal environment: MacOS
- Command you ran: nodemon --inspect

### Expected behaviour
Expect to run `node --inspect index.js`. It should work without specifying the default JS file (`nodemon` should look for the file defined in "main").

### Actual behaviour
It runs `node index.js --inspect` which doesn't start the debugger. It works only if i specify the JS file with `nodemon --inspect index.js`.

### Steps to reproduce
Just run `nodemon --inspect`

---

If applicable, please append the `--dump` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens**.

**Comment by remy** [comment]
Question: how does nodemon know that `--inspect` should go to the exec and not your script?

**Comment by eilgin** [comment]
I only found this in the [README](https://github.com/remy/nodemon#usage) (which i believe is also the only doc):
> If no script is given, nodemon will test for a package.json file and if found, will run the file associated with the main property

Moreover it says later that the "`inspect` flag [is passed] to node" so i'm confused by your question since the default behavior **seems** to use the "main" value from `package.json` (if found) and `--inspect` is a flag passed to the executed `node` process therefore `nodemon --inspect` should be interpreted as `nodemon --inspect <file referenced by require('./package.json').main>`?

Anyway i'm using the explicit version now.

**Comment by remy** [comment]
The `main` value is used, but the problem is quite subtle. Firstly, the `exec` may not be node, other developers might be using a different tools, so I can't assume to pass `--inspect` to the exec.

Equally, I'd have to (to my knowledge) manually maintain a list of node arguments and filter for them and pass them across if present. Other tools (and nodemon) have tried this in the past, but when new flags are added to node, the tool doesn't know about them and thus doesn't pass them (i.e. `--inspect` is relatively new, and wasn't in previous versions).

If there was a way to iterate and maintain the list of supported node args, then there might be a dynamic solution. Though, I'm not totally against hard coding some common flags into nodemon, like `--inspect`, `--trace-warnings`, etc - but I'd like to get some shared input on which would be worth supporting.

**Comment by remy** [comment]
Thinking aloud (as it were), _maybe_, if there's no script arguments to nodemon, it should pass everything (in order) to the `exec` process.

This would solve the issue of edge cases like if something like `--zero-fill-buffers` isn't hardcoded. And if you want to stop slurping args, you can use the double-dash method.

ie, this would be possible:

```
nodemon --inspect -- --inspect
# node --inspect index.js --inspect
```

Thoughts?

**Comment by eilgin** [comment]
I like the idea of the `--`. It feels in accordance to the unix tools 👍

**Comment by remy** [comment]
@eilgin nodemon has always supported the `--` flag, to avoid slurping up args that nodemon used and your scripts used - just making sure it works for the arg-less invocation too.

**Comment by eilgin** [comment]
I didn't know that, i've started using `nodemon` only 2 days ago 😄

**Comment by valoricDe** [comment]
In version 1.19.2 the `nodemon --inspect -- --inspect` does not work.
So when I run `nodemon --inspect --delay 200ms -- --inspect` it seems to pick my start script `"start": "node -r esm -r dotenv/config ./bin/www",` and translate it to `node -r esm -r dotenv/config ./bin/www --inspect --inspect`. Therefore I wonder why this ticket is closed. Is it a regression or has there been issues with this approach?
