### ISSUE TITLE
Delay first start of nodemon

### ISSUE THREAD

**Issue by kkorus** [remy/nodemon#1264]
So it is possible to delay nodemon restarting by using `--delay`, but is it possible to delay just first start of nodemon and then have restarting without delays?

**Comment by remy** [comment]
Maybe with `sleep 10 && nodemon`? Otherwise, not through nodemon's existing flags, no.

**Comment by lonix1** [comment]
This would be a great solution to multiple restarts upon the first start - because typescript hasn't finished compiling yet, so nodemon restarts again and again and again. Once it's up and running, everything is then okay.

The `sleep 10` is a nice workaround but would be cool if it were a self-contained solution.
