### ISSUE TITLE
If restart script exits with > 0, do not restart main script

### ISSUE THREAD

**Issue by ORESoftware** [remy/nodemon#1277]
- `nodemon -v`: **1.17.1**
- `node -v`: **9.2.0**
- Operating system/terminal environment: 
- Command you ran:

I have this in `nodemon.json`:

```json
  "events": {
    "restart": "./scripts/nodemon/restart.sh"
  },
```

In my restart.sh, I have:

```bash
already_running="$(pgrep -f 'bash ./scripts/tsc.sh')"

if [[ -z "$already_running" ]]; then
    echo "You need to run ./scripts/tsc.sh before running ./scripts/run.sh";
    exit 1;
fi
```

### Expected behaviour
I would expect that if the restart.sh script exits with 1 instead of 0, that my main script would not get executed. Nodemon would wait for another "rs" or file change event to retry.

### Actual behaviour
Even if the restart script exits with 1, nodemon doesn't change behavior.

**Comment by remy** [comment]
I'd recommend you capture the exit code and manipulate before it goes to nodemon using this technique: https://github.com/remy/nodemon/blob/master/faq.md#error-process-failed-unhandled-exit-code-2

I'm going to close the issue because I believe this is fairly solid solution (I've used it myself in some cases).
