### ISSUE TITLE
--watch nulls --ignore for subdirectories created after starting nodemon

### ISSUE THREAD

**Issue by arthurwhite** [remy/nodemon#1281]
Seems related to #574.

### Steps to reproduce

1. Create a dummy server (*server.js*) inside a directory (*dist*):
  `mkdir dist && touch dist/server.js`

2. Set nodemon to only watch the directory (*dist*), but ignore a subdirectory that doesn't yet exist (*dist/public*):
  `nodemon --watch dist --ignore dist/public dist/server.js`

3. Create the subdirectory that should be ignored (*dist/public*), and a file inside (*client.js*):
  `mkdir dist/public && touch dist/public/client.js`

4. Modify the file (*client.js*) in the "ignored" directory (*dist/public*):
  `touch dist/public/client.js`

5. 💥 nodemon restarts the server

If the entry file (*server.js*) is in the root of the project (so `--watch` is not used), `--ignore` is respected even for directories created after starting nodemon.

### Stack

- nodemon 1.17.1
- Node 9.6.1
- macOS High Sierra 10.13.3 (17D102)

**Comment by remy** [comment]
I'm not 100% I can provide a fix (internally) for this, but if the `dist/public` directory is in place _before_ you start nodemon (and it can be empty), then it won't restart.

Behind the scenes, it's because nodemon is using chokidar library to watch for changes, and "ignore" means don't want for changes in this directory. Since the directory doesn't exist, chokidar doesn't have to do anything, but when the `public` directory comes into existence it triggers the reload (as you saw).

Is this a viable work around?

**Comment by arthurwhite** [comment]
That's what I resigned myself to doing.

Previously, I wanted to directly run parallel watching tasks with nodemon and webpack for this project structure:
```
dist/
  public/
    app.bundle.js
  server.js
src/
  public/
    scripts/
      app.ts
    styles/
      app.scss
  server.ts
```
But as webpack creates `dist/public` after nodemon starts to watch `dist`, I must always be sure that the entire project is built before starting watchers.

If no solution exists, I think we can close the issue.

**Comment by remy** [comment]
Okay, your webpack use makes sense. Let me take a look at the chokidar docs in a bit more detail to see if there's anything I've missed.

**Comment by remy** [comment]
I've got a PR for this, but it's failing tests, so it's on the back burner for the time being.
