### ISSUE TITLE
use a comma as extension separator in the config file as it is in the CLI

### ISSUE THREAD

**Issue by capaj** [remy/nodemon#1306]
for some reason when configuring extensions to be watched in a config file, nodemon accepts input like this: `js json` but when inputting same thing over CLI, it accepts it like: `js, json`

why this discrepancy? Could this be unified?

**Comment by remy** [comment]
Actually, `js, json` isn't valid on the command line. These are:

- `js,json` (no space)
- `"js json"
- `"js, json"

It's to catch mistakes by the user. But you _can't_ use `--ext js json` on the command line because it doesn't know when the options to `ext` have finished, so it needs to be a discrete string.

**Comment by capaj** [comment]
I know how bash works, thanks for pointing it out, but I still think it would be nicer if it was always just comma separated-on CLI and in the config file.
