### ISSUE TITLE
Donation Script Breaks Windows Install

### ISSUE THREAD

**Issue by crash99** [remy/nodemon#1333]
When installing to my Windows 10 Home machine with npm, the script which prints a donation request causes an error and npm deletes all of the data it just installed. I happens in powershell, cmd, and git bash. The cause of the error is a bash style logical OR. As this is not supported by Windows the installation fails. A workaround is using the --ignore-scripts flag however this is unnecessarily clunky and obscure.

![image](https://user-images.githubusercontent.com/16692923/39648178-961c9128-4faf-11e8-9fdd-57c6b2ca0b5c.png)
![image](https://user-images.githubusercontent.com/16692923/39648172-88d3664a-4faf-11e8-8717-b9ae4cc168a7.png)
![image](https://user-images.githubusercontent.com/16692923/39648824-9962a398-4fb1-11e8-9e06-9821cf1952d0.png)

**Comment by remy** [comment]
That output looks like powershell (though I'm not a regular user of Windows, so please correct me if I'm wrong).

Are you certain is fails under cmd and git bash? Only because I've tested nodemon in these environments (but can't remember specifically if I had run a full install), but it also feels fishy if this always fails and yet this is first I'm hearing from it (for which I appreciate - and will fix!).

If you're able to double check in git bash for me I'd appreciate it, otherwise I can try to take a look next week (I'm away this w/e with the family).

**Comment by crash99** [comment]
The screenshots are from git bash. I tested it under all three prompts and they fail the same way. Apologies for the late response as I was busy with personal issues.
