### ISSUE TITLE
nodemon can't install, using yarn, with node > 9 due to upath package

### ISSUE THREAD

**Issue by RandallFlagg** [remy/nodemon#1369]
- `nodemon -v`: `latest`
- `node -v`: `10.1.0`
- Operating system/terminal environment: `Windows 10 64-bit`
- Command you ran: `yarn global add nodemon`

### Expected behaviour
nodemon is installed

### Actual behaviour (Command line output)
```
yarn global v1.7.0
[1/4] Resolving packages...
⠂ nodemon(node:3188) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
[2/4] Fetching packages...
error upath@1.0.2: The engine "node" is incompatible with this module. Expected version ">=4 <=9".
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/global for documentation about this command.
```

### Steps to reproduce
1. use node 10
3. yarn global add nodemon

---

If applicable, please append the `--dump` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens**.

**Comment by edorivai** [comment]
Seems it's fixed in chokidar already: https://github.com/paulmillr/chokidar/commit/11aea72ad7c65216a0f767142ce57151c7b3d0c1#diff-b9cfc7f2cdf78a7f4b91a753d10865a2.

They published a new patch version (`2.0.4`), so reinstalling nodemon might work, depending on your npm client and whether you have other dependencies on chokidar.

Maybe nodemon could bump the chokidar dependency to `2.0.4`, so bumping nodemon to the latest version would definitely fix it.

**Comment by remy** [comment]
nodemon's dep version on chokidar allows for patch changes IIRC, so a it sounds like a clean install should fix it?

**Comment by edorivai** [comment]
Yeah, it does fix it. But if you are using yarn and have other packages that already depend on chokidar, the clean install of nodemon will not update the version of chokidar.
