### ISSUE TITLE
Windows and lack of signals -> graceful shutdown

### ISSUE THREAD

**Issue by TimNZ** [remy/nodemon#140]
nodemon sends a SIGUSR2 signal on terminate that Windows doesn't handle.

Any using nodemon on windows and has a tidy alternative for graceful shutdown?

Production deploy will be linux, but I dev on Windows and want to test.

I can think of some things but they would require modifying nodemon.

**Comment by gwilakers** [comment]
So nothing on this then?

**Comment by errorx666** [comment]
I'd like this to be reopened.

At least note the limitation in the docs.  I spent most of this morning trying to figure out why I wasn't seeing the SIGUSR2 signal in my app.

**Comment by remy** [comment]
I'm not reopening a 5 year old issue. The code that caused this bug has long gone and it's extremely likely you're seeing something new. Can you file a new issue with full details on how to replicate, ideally with any investigation too.

**Comment by errorx666** [comment]
@remy It looks like the issue was closed a month and a half ago as `wontfix`, so it didn't appear as though it was gone.  From the discussion, it sounds like the documented solution for a graceful shutdown of listening for a `SIGUSR2` signal is not actually supported on Windows.

Are you saying that this is no longer the case?

**Comment by remy** [comment]
I've no idea, I use Windows on the odd occasion to debug nodemon issues, otherwise I'm a Mac user. So when windows issues come up, I've had to rely in the past on others to give me details.

The wontfix was because the issue was idle, and like I said, the code that the original issue was raised on doesn't exist due to redactors over the (five) years since it was originally raised.

But, as I said, if you raise a new issue, with details on how to replicate then I can investigate. I'm doing some windows test and bug fixing today too.
