### ISSUE TITLE
[Feature Request] Automatically reload server on crash without file modification

### ISSUE THREAD

**Issue by stevefan1999** [remy/nodemon#1415]
So I was looking to workaround this problem: https://github.com/nestjs/typeorm/issues/41, I was thinking to use a nodemon/webpack HMR hybrid: Whenever the server crashed, nodemon will respawn it again, and the majority of the reload work is done by HMR but I'm very surprised at the fact nodemon will not restart without file modification, rendering my scheme impossible. I know that it somewhat violates the philosophy of nodemon but can you reconsider letting the server restart on crash without looking for file modification?

**Comment by remy** [comment]
I'd rather see this solved with some middleware like functionality. Only because many people use nodemon for non-node web development. ie. Go based servers, or build systems, or tests, etc. 

So hot reload solvers a specific problem (that's been solved well elsewhere). I wonder if live-reload and nodemon can be combined (for instance) to solve this?

**Comment by stevefan1999** [comment]
[I had adapted to use this plugin instead](https://www.npmjs.com/package/nodemon-webpack-plugin). In a nutshell it still uses nodemon but it watches for webpack `afterEmit` event. My app contains global state, so I have had to live reload, and it also means HMR is meaningless now. Closing this as solved.
