### ISSUE TITLE
Solution for Monorepo / Lerna and new NPM file:// dependency support

### ISSUE THREAD

**Issue by andrewcharnley** [remy/nodemon#1483]
Hi,

Previously Lerna used symlinks within the node_modules folder which nodemon would follow. Following recent(ish) changes the updated approach is to include the packages as dependencies using the NPM file:// notation, such as:

`  "dependencies": {
    "@j13k/dal-dbx-file": "file:../../packages/dal-dbx-file",
    "@j13k/lib-errors": "file:../../packages/lib-errors",
    "@j13k/lib-loaders": "file:../../packages/lib-loaders",
    "@j13k/process-manager": "file:../../packages/process-manager",
    "@j13k/logger-stdx": "file:../../packages/logger-stdx",
    "compression": "^1.7.3",
    "colors": "^1.1.2",
    "cors": "^2.8.5",
    "express": "^4.16.2",
    "helmet": "^3.15.0",
    "swagger-tools": "^0.10.1"
  },

In my case I need to monitor changes to the ../../packages folder(s) and restart, however traversing parent directories does not work (using 1.18.7). 

I thought nodemon worked by watching files included by require which is the ideal approach here. My service requires many files within these packages but looks to have the same limitation with being unable to follow to a parent folder (unless symlinked).

Regards, Andrew

**Comment by remy** [comment]
nodemon doesn't follow your deps, which is why it isn't picking up these changes. You need to tell nodemon to watch the directory if it's outside the current working directory.

You should be able to solve this with the `watch` option and a `nodemon.json` file. I'm on mobile ATM otherwise I'd give you a link to the example config (but it's in the readme-somewhere). 

I'll close for now as I think you've got what you need.

**Comment by andrewcharnley** [comment]
Perhaps you could allow your users the formality of a small timeframe to respond before closing the issue.

The issue stands.  **Traversing parent directories does not work (using 1.18.7).** using the --watch command does not work.

**Comment by remy** [comment]
Github has a nice feature that allows me to reopen issues if required.

You'll need to provide your nodemon.json (as I said, I'm fairly sure it can be solved using that file), and if there's a bug, I'm *more* than happy to reopen this issue for a PR to be attached to it (I'm closing the dupe for now and will continue on this thread).

Here, by the way, is a screenshot of watching the cwd and a different parent directory - and then touching the _other_ directory file and nodemon restarting.

<img width="824" alt="screen shot 2018-12-10 at 18 20 24" src="https://user-images.githubusercontent.com/13700/49752483-6b515e00-fca8-11e8-947a-47ea8d10362b.png">

So without any additional information on your part, I can only assume you're missing the file I've suggested you include and that's why it's not working for you.
