### ISSUE TITLE
problem with vscode debug mode

### ISSUE THREAD

**Issue by javadbat** [remy/nodemon#1503]
see 

https://github.com/Microsoft/vscode/issues/65163

**Comment by marcospgp** [comment]
I'm not sure if this is related, but I was setting up VSCode debugging with nodemon and docker and it wasn't working properly.

I noticed my start command was `./node_modules/.bin/nodemon --legacy-watch --inspect=0.0.0.0:9222 --nolazy --ignore public/` instead of `./node_modules/.bin/nodemon --legacy-watch --inspect=0.0.0.0:9222 --nolazy --ignore public/ app.js` (note the missing file name at the end).

This fixed the problem and it now works just fine.

This is the output I got with the wrong command:

```
web_1            | [nodemon] starting `node app.js --inspect=0.0.0.0:9222`
web_1            | ✓ App is running at http://localhost:8080 in development mode
```

and this is the output I get with the right command:

```
web_1            | [nodemon] starting `node --inspect=0.0.0.0:9222 --nolazy app.js`
web_1            | Debugger listening on ws://0.0.0.0:9222/d6b49a0a-5a45-4ee6-937d-d92e538584f6
web_1            | For help see https://nodejs.org/en/docs/inspector
web_1            | ✓ App is running at http://localhost:8080 in development mode
```

**Comment by javadbat** [comment]
the different is I don't use docker

**Comment by remy** [comment]
I don't either. Again, can you provide replication details without gulp?
