### ISSUE TITLE
watching 0 files

### ISSUE THREAD

**Issue by lobopl** [remy/nodemon#1542]
I am using nestjs cli to generate project, in dev mode it is dependant to nodemon, but for some reason nodemon doesn't see any files to watch. Essentialy issue is only with nodemon watcher

- Node v11.12.0 checked also on 8.x
- Platform Windows 10 Home 64bit
- Nodemon 1.18.10 checked also lower version till 1.18.1

### Expected behaviour
files in src are properly watched and after each change code is executed

### Actual behaviour
files are not watched, initial exec is executed properly

### Steps to reproduce
<pre><code>
npm i -g @nestjs/cli
nest new project-name
cd project-name
npm run start:dev
</code></pre>

nodemon.json
<pre><code>
{
  "watch": ["src"],
  "ext": "ts",
  "verbose": true,
  "ignore": ["src/**/*.spec.ts"],
  "exec": "ts-node -r tsconfig-paths/register src/main.ts"
}
</code></pre>
src contains only 5 ts files

console output:
<pre><code>
[nodemon] 1.18.10
[nodemon] reading config .\nodemon.json
[nodemon] to restart at any time, enter `rs`
[nodemon] or send SIGHUP to 15448 to restart
[nodemon] ignoring: src/**/*.spec.ts
[nodemon] watching: C:\projekty\nest\src/**/*
[nodemon] watching extensions: ts
[nodemon] starting `ts-node -r tsconfig-paths/register src/main.ts`
[nodemon] spawning
[nodemon] child pid: 3672
[nodemon] watching 0 files
</code></pre>

output with dump
<pre><code>
> nest@0.0.1 start:dev C:\projekty\nest
> nodemon --dump

[nodemon] 1.18.10
[nodemon] reading config .\nodemon.json
[nodemon] to restart at any time, enter `rs`
[nodemon] or send SIGHUP to 19268 to restart
[nodemon] ignoring: src/**/*.spec.ts
[nodemon] watching: C:\projekty\nest\src/**/*
[nodemon] watching extensions: ts
--------------
node: v11.12.0
nodemon: 1.18.10
command: C:\Program Files\nodejs\node.exe C:\projekty\nest\node_modules\nodemon\bin\nodemon.js --dump
cwd: C:\projekty\nest
OS: win32 x64
--------------
{ run: false,
  system: { cwd: 'C:\\projekty\\nest' },
  required: false,
  dirs: [ 'C:\\projekty\\nest\\src' ],
  timeout: 1000,
  options:
   { dump: true,
     watch: [ 'src', re: /src/ ],
     verbose: true,
     ignore:
      [ '**/.git/**',
        '**/.nyc_output/**',
        '**/.sass-cache/**',
        '**/bower_components/**',
        '**/coverage/**',
        '**/node_modules/**',
        'src/**/*.spec.ts',
        re: /.*.*\/\.git\/.*.*|.*.*\/\.nyc_output\/.*.*|.*.*\/\.sass\-cache\/.*.*|.*.*\/bower_components\/.*.*|.*.*\/coverage\/.*.*|.*.*\/node_modules\/.*.*|src\/.*.*\/.*\.spec\.ts/ ],
     exec: 'ts-node -r tsconfig-paths/register src/main.ts',
     ignoreRoot:
      [ '**/.git/**',
        '**/.nyc_output/**',
        '**/.sass-cache/**',
        '**/bower_components/**',
        '**/coverage/**',
        '**/node_modules/**' ],
     restartable: 'rs',
     colours: true,
     execMap: { py: 'python', rb: 'ruby' },
     stdin: true,
     runOnChangeOnly: false,
     signal: 'SIGUSR2',
     stdout: true,
     watchOptions: {},
     execOptions:
      { script: null,
        exec: 'ts-node -r tsconfig-paths/register src/main.ts',
        args: [],
        scriptPosition: null,
        nodeArgs: undefined,
        execArgs: [],
        ext: 'ts',
        env: {} },
     monitor:
      [ 'C:\\projekty\\nest\\src/**/*',
        '!**/.git/**',
        '!**/.nyc_output/**',
        '!**/.sass-cache/**',
        '!**/bower_components/**',
        '!**/coverage/**',
        '!**/node_modules/**',
        '!src/**/*.spec.ts' ] },
  load: [Function],
  reset: [Function: reset],
  lastStarted: 0,
  loaded: [ 'C:\\projekty\\nest\\nodemon.json' ],
  watchInterval: null,
  signal: 'SIGUSR2',
  command:
   { raw:
      { executable: 'ts-node -r tsconfig-paths/register src/main.ts',
        args: [] },
     string: 'ts-node -r tsconfig-paths/register src/main.ts' } }
--------------
[nodemon] exiting

Process finished with exit code 0
</code></pre>

**Comment by lobopl** [comment]
Same issue with simpler configuration without typescript so

repo structure
<pre><code>
/src
/src/index.js
nodemon.json
package.json
</code></pre>

index.js
<pre><code>
console.log('test');
</code></pre>

nodemon.json
<pre><code>
{
  "watch": ["src"],
  "exec": "node src/index.js",
  "verbose": true
}
</code></pre>

package.json
<pre><code>
{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "watch": "nodemon"
  },
  "author": "",
  "license": "ISC"
}
</code></pre>

output
<pre><code>
[nodemon] 1.18.10
[nodemon] reading config .\nodemon.json
[nodemon] to restart at any time, enter `rs`
[nodemon] or send SIGHUP to 1668 to restart
[nodemon] watching: C:\projekty\nodemon\src/**/*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node src/index.js`
[nodemon] spawning
[nodemon] child pid: 14112
[nodemon] watching 0 files
test
[nodemon] clean exit - waiting for changes before restart
</code></pre>

no autorefresh after change

**Comment by syedsameerali** [comment]
I am facing a similar issue, where nodemon is not restarting the node process on file changes.

I first noticed the issue beginning Friday, March 22, 2019

The Issue I believe is related to the nodemon packages dependencies, I believe following the aforementioned date, breaking changes were introduced to one of nodemons dependencies. 
Please note I am far from experienced with node/javascript, I apologize if I am mistaken, I just wanted to share what my experience has been in the past few days, hoping it might be relevant.

---

⬛ nodemon Version: 1.18.10

⬛ node Version: v11.12.0

⬛ OS Name: Microsoft Windows 10 Home

⬛ OS Version: 10.0.17763 Build 17763

⬛ Terminal(s) environment: Windows Command Prompt, Bash 4.4.23(1)-release, VsCode integrated terminal (Bash 4.4.23(1)-release)

⬛ Expected behavior:

On file change(s) nodemon  restarts the node process without invoking the manual restart command `rs`.

⬛ Actual behavior:

nodemon does not restart the node process on file change(s). It is necessary to invoke the `rs` command in the terminal to restart the node process.

⬛ Steps to reproduce:

Please view screen recording:

https://youtu.be/NJz8iLP5U_E 

⬛ Log Dump:
--------------
node: v11.12.0
nodemon: 1.18.10
command: E:\_Bin\nodejs\node.exe F:\_Projects.local\_Learning\nodemon-test\node_modules\nodemon\bin\nodemon.js ./index.js --dump
cwd: F:\_Projects.local\_Learning\nodemon-test
OS: win32 x64
--------------
{ run: false,
  system: { cwd: 'F:\\_Projects.local\\_Learning\\nodemon-test' },
  required: false,
  dirs: [ 'F:\\_Projects.local\\_Learning\\nodemon-test' ],
  timeout: 1000,
  options:
   { dump: true,
     ignore:
      [ '**/.git/**',
        '**/.nyc_output/**',
        '**/.sass-cache/**',
        '**/bower_components/**',
        '**/coverage/**',
        '**/node_modules/**',
        re: /.*.*\/\.git\/.*.*|.*.*\/\.nyc_output\/.*.*|.*.*\/\.sass\-cache\/.*.*|.*.*\/bower_components\/.*.*|.*.*\/coverage\/.*.*|.*.*\/node_modules\/.*.*/ ],
     watch: [ '*.*', re: /.*\..*/ ],
     ignoreRoot:
      [ '**/.git/**',
        '**/.nyc_output/**',
        '**/.sass-cache/**',
        '**/bower_components/**',
        '**/coverage/**',
        '**/node_modules/**' ],
     restartable: 'rs',
     colours: true,
     execMap: { py: 'python', rb: 'ruby' },
     stdin: true,
     runOnChangeOnly: false,
     verbose: false,
     signal: 'SIGUSR2',
     stdout: true,
     watchOptions: {},
     execOptions:
      { script: './index.js',
        exec: 'node',
        args: [],
        scriptPosition: 0,
        nodeArgs: undefined,
        execArgs: [],
        ext: 'js,mjs,json',
        env: {} },
     monitor:
      [ '*.*',
        '!**/.git/**',
        '!**/.nyc_output/**',
        '!**/.sass-cache/**',
        '!**/bower_components/**',
        '!**/coverage/**',
        '!**/node_modules/**' ] },
  load: [Function],
  reset: [Function: reset],
  lastStarted: 0,
  loaded: [],
  watchInterval: null,
  signal: 'SIGUSR2',
  command:
   { raw: { executable: 'node', args: [ './index.js' ] },
     string: 'node ./index.js' } }
--------------

**Comment by syedsameerali** [comment]
Update: As of this moment the issue seems to have been resolved. By re-installing the nodemon package, everything is working normally.

**Comment by lobopl** [comment]
Yes it started working properly, i will close this issue
