### ISSUE TITLE
Want to conditionally exit nodemon

### ISSUE THREAD

**Issue by babbott1000** [remy/nodemon#1556]
My Environment is:
```
Nodemon Version: 1.18.11
Node Version: v10.15.3
Win 10 64-bit
```

My `nodemon.json` is as follows
```
{
	"restartable": "rs",
	"ignore": [
		"client"
	],
	"events": {
		"start": ".\\node_modules\\.bin\\webpack --config webpack.prod.js",
		"exit": "exit"
	},
	"verbose": true
}
```

I am trying to make Nodemon quit when my program executes `process.exit(0);`.  What actually happens is Nodemon prints 
```
[nodemon] clean exit - waiting for changes before restart
```
then continues on.  I tried putting an echo 6 in place of the exit command
```
{
	"restartable": "rs",
	"ignore": [
		"client"
	],
	"events": {
		"start": ".\\node_modules\\.bin\\webpack --config webpack.prod.js",
		"exit": "echo 6"
	},
	"verbose": true
}
```
and that printed 6 whenever the program exiting with exit code 0.

**Comment by viditvarshney** [comment]
You want to quit nodemon when your program executed ?

**Comment by babbott1000** [comment]
I want to exit nodemon when my program exits if the exit code is not 1

**Comment by remy** [comment]
@babbott1000 this (not exiting nodemon on `exit(0)`) is intended behaviour. The purpose of nodemon is for development to keep your process running and restarting.

I suspect that a custom bit of logic around nodemon is what you need (via the required version of nodemon). I've got some time today where I might be able to codify this for you, otherwise this issue is more of a feature request which I'm sorry to say, doesn't fit with nodemon's design principles.

I'll ping back here if I'm able to solve today with some code.

**Comment by jbinto** [comment]
@remy Would be great to hear if there's a workaround to convince `nodemon` to exit itself from within a running app. It looks like `process.exit(2)` used to work but then a 500ms throttle was added.
