### ISSUE TITLE
Deployment process - Swaps folder - Monitoring

### ISSUE THREAD

**Issue by rohanabraham** [remy/nodemon#1585]
Great tool, thanks!

I run nodemon like this

> nodemon --watch /full_path_to_live_code_directory/ /full_path_to_live_code_directory/index.js 

Our deployment process uses a folder swap. After the new folder is ready, the deployment process swaps the folder and swaps out the old folder to _old_folder. 

mv /full_path_to_live_code_directory/ /full_path_to_OLD_code_directory
mv /full_path_to_NEW_code_directory/ /full_path_to_live_code_directory

It turns out that nodemon monitors the folder that is swapped out. 

### Expected behaviour
The new folder has the new files so that should be monitored

### Actual behaviour
The folder is reported to have no changes.
Making a change to the files in the old directory causes nodemon to restart but it is still looking at the old folder.

### Steps to reproduce
Above

---

If applicable, please append the `--dump` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens**.

**Comment by rohanabraham** [comment]
Hey @remy would like to hear your thoughts on this.

**Comment by remy** [comment]
A few thoughts:

- This sounds like you're using nodemon in production (to watch a deployment dir), which…you really shouldn't (since it's a devtool). (possibly I'm wrong)
- More pertinent, when nodemon starts, it watches the directories. When it restarts the sub process, nodemon doesn't reload it's configuration.
- There's a documented event that you should be able to send to nodemon to reload the config but I can't see that it's implemented anywhere, but I don't think it would help your situation anyway (since you're not requiring nodemon, but running on the command line).

Otherwise I believe you should stop and restart nodemon directly. Nodemon's own PID is included in the logging so you can use that.

Not perfect, but I think you're working in a very small edge case.
