### ISSUE TITLE
Nodenom not Working

### ISSUE THREAD

**Issue by SerenModz21** [remy/nodemon#1596]
I installed nodemon like it tells you to with `npm i nodemon` but when i go to use nodemon commands like `nodemon index.js` or `nodemon -v` it says `'nodemon' is not recognised as an internal or external command, operable program or batch file.`

Im running the following:
• node v12.2.0
• npm v6.10.1
• windows 10

the terminals ive tried this with:
• command prompt
• cmder
• git bash
• power-shell

![Nodemon](https://user-images.githubusercontent.com/41450647/63145589-e1545480-bfef-11e9-8614-74c6fff0f3db.PNG)

**Comment by etc-tiago** [comment]
Try using ./node_modules/.bin/nodemon and let us know if it worked…

**Comment by SerenModz21** [comment]
![image](https://user-images.githubusercontent.com/41450647/63205615-0784fd80-c09f-11e9-98ee-c2aaa304f524.png)

**Comment by darwishmammo** [comment]
I have the same problem here

**Comment by SerenModz21** [comment]
But the problem i have to keep putting the nodemon and .bin folders into node_modules and a load of other folders that it asks for and it can get really annoying

**Comment by darwishmammo** [comment]
I updated Node from 10.16.0 to 10.16.3 and now it works again fine.

**Comment by Vulplion** [comment]
> 
> 
> I updated Node from 10.16.0 to 10.16.3 and now it works again fine.

I have the same issues as you guys, never have had this issue before. I am currently on 10.16.3 although and its still broken.

**Comment by remy** [comment]
This issue is related to your node configuration. It's not be set to work for globally installed files (not sure how though, I don't use windows).

That error is telling you that Windows doesn't know how to execute the `nodemon` command. If you try `node ./node_modules/.bin/nodemon` I'm pretty sure it'll work (I'll reopen this issue if it doesn't).

If prefixing with node, it means that there's a machine setup problem, rather than nodemon.

If it doesn't work prefixed with node, then there's something else at play and I'll reopen.

**Comment by schivmeister** [comment]
Something is very wrong. I install Node for Windows using the official installer (without installing the additional tools). I run the global install command for nodemon. I see there is a new folder for nodemon in the relevant global node_modules folder. However, Windows (8.1) still cannot find nodemon.

Windows can execute node itself because there is a batch file for it. However, aside from a couple of other batch files, there's no other executable, and no executable for nodemon. The nodemon binary is not a binary but a JavaScript file. Nevertheless, there's nothing equivalent to a wrapper that runs node nodemon post-install.

**Comment by katarisrividya** [comment]
> This issue is related to your node configuration. It's not be set to work for globally installed files (not sure how though, I don't use windows).
> 
> That error is telling you that Windows doesn't know how to execute the `nodemon` command. If you try `node ./node_modules/.bin/nodemon` I'm pretty sure it'll work (I'll reopen this issue if it doesn't).
> 
> If prefixing with node, it means that there's a machine setup problem, rather than nodemon.
> 
> If it doesn't work prefixed with node, then there's something else at play and I'll reopen.

It worked thank you

**Comment by Martin2381** [comment]
Hi, just looking for help and wondering why node keeps crashing if any suggestions to help here is my message.
I keep receiving after running nodemonat Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
[nodemon] app crashed - waiting for file changes before starting...

**Comment by serhatates** [comment]
> ![image](https://user-images.githubusercontent.com/41450647/63205615-0784fd80-c09f-11e9-98ee-c2aaa304f524.png)
> 
> it didnt work in cmd but when i tried it in git bash, it worked
> then i put it in a bat file and that also worked

you have to do `C:\>"./node_modules/.bin/nodemon" -v`     
in windows
""

**Comment by joe-oli** [comment]
Actually in 2021 I had the same problem, the DOCS should be made explicit to tell Windows users to use back-slash
$./node_modules/.bin/nodemon
should be ON WINDOWS 
>.\node_modules\.bin\nodemon

** Does not only apply to this Lib only, lots of examples, tutes out there are written by a Mac/Linux user for other Mac/Linux users.

**Comment by SnoogySocks** [comment]
http://5.9.10.113/63999376/windows-how-to-fix-nodemon-node-js

**Comment by paragkadyan** [comment]
any fix yet?
