### ISSUE TITLE
passing --inspect to node

### ISSUE THREAD

**Issue by valoricDe** [remy/nodemon#1612]
In version 1.19.2 debugging with
```
"script": {
"start": "node -r dotenv/config ./bin/www",
"dev": "nodemon --inspect"
}
```
does not start node like `node --inspect -r dotenv/config ./bin/www`.
So when I run nodemon --inspect --delay 200ms -- --inspect it seems to pick my start script "start": "node -r esm -r dotenv/config ./bin/www", and translate it to node -r esm -r dotenv/config ./bin/www --inspect --inspect. Therefore I wonder why this ticket is closed. Is it a regression or has there been issues with this approach?

**Comment by valoricDe** [comment]
Can anybody aggree or should I look more deeply into my honeypot of code?

**Comment by toddheslin** [comment]
Hey @valoricDe I've had plenty of time messing around with these configs. Try this:
```
"script": {
    "start": "node -r dotenv/config ./bin/www",
    "debug": "nodemon --exec \"node -r dotenv/config --inspect\" ./bin/www",
}
```

**Comment by valoricDe** [comment]
Thank you, yes I helped me also with duplicating my start script with
`"start:dev": "node --inspect -r dotenv/config ./bin/www",` and call
`nodemon --watch dist --delay 200ms --exec yarn start:dev`
But it's strange that it is advertised in the readme that it should "just work"

**Comment by toddheslin** [comment]
Yep, the key is that the `--inspect` flag needs to be passed to the `node` process and not the `nodemon` process. Hopefully this thread helps others work it out too.

**Comment by remy** [comment]
To add further to this, it's because `node` needs the `--inspect` flags to appear _before_ the filename. When nodemon is building up the execution itself, then I can put the `--inspect` in front of the filename, but when it's not able to find the file and defers to `npm start` it's not able to pass it in.

Basically, the permutations of arguments is impossible to support, so it "just works" on simple use, advanced use: you have to jump a few hoops.
