### ISSUE TITLE
Nodemon does not start

### ISSUE THREAD

**Issue by diegolg13** [remy/nodemon#1616]
my package.json

{
  "name": "backend",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "scripts": {
    "dev": "nodemon src/server.js"
  },
  "dependencies": {
    "express": "^4.17.1",
    "mongoose": "^5.7.3",
    "multer": "^1.4.2"
  },
  "devDependencies": {
    "nodemon": "^1.19.3"
  }
}
Nodemon restarting due to changes..., not starting. 
Nodemon does not start. I'm using Win 10

**Comment by remy** [comment]
I'm afraid there's not enough information to be able to help you out here. I've no idea of the _actual_ output - your issue says it doesn't start, but the line "Nodemon restarting due to changes" suggests it did start.

Then there's the `src/server.js` and what that contains - it's possible that it's trapping, but it's just a guess.

This issue will likely auto close unless there's additional information.
