### ISSUE TITLE
Prevent restarting unless crashed

### ISSUE THREAD

**Issue by slikts** [remy/nodemon#1650]
Being able to avoid restarting the process unless it exited with an error code would be useful in some situations; a specific motivating example is [NodeGui], which uses webpack with HMR for development, so restarting the process is only necessary if it crashes.

There have been similar feature requests before, but they were better served with tools like forever or pm2, but they don't work for use cases where the restart should be based on file changes to avoid going into a loop.

[NodeGui]: https://github.com/nodegui/nodegui

**Comment by shamilovtim** [comment]
also having this issue. need a feature that prevents restart. `delay` isn't good enough because it delays actually starting the process. what i want is the ability to stop the process from running again while it's running. if that means not batching it then that's still preferable to the way it works now.
