### ISSUE TITLE
dependency to vulnerable component undefsafe 2.0.2

### ISSUE THREAD

**Issue by othen** [remy/nodemon#1680]
- `nodemon -v`: 2.0.2
- `node -v`: n/a
- Operating system/terminal environment: n/a
- Using Docker? What image:  n/a
- Command you ran: n/a

### Expected behaviour

Use undefsafe 2.0.3 instead of 2.0.2 as dependency in your package.json
### Actual behaviour
undefsafe 2.0.2 is used

### Steps to reproduce

---
Please have a look at this vulnerability with undefsafe 2.0.2:
https://nvd.nist.gov/vuln/detail/CVE-2019-10795

**Comment by remy** [comment]
Would be great if people bothered understanding dependencies and vulnerabilities in code before filing these issues…

Firstly, *your* code might have the vuln, but refreshing your deps (doing a fresh install of nodemon at the exact same version that you're using) will pull the latest undefsafe which doesn't carry the potential vuln. A simple check of the package shows that.

Undefsafe was upgraded 4 days ago prior to the vulnerability being released: https://snyk.io/vuln/npm:undefsafe 

You're not the first to file issues like this without really checking whether nodemon still carries the vuln, and you certainly won't be the last - which is why my tone is a touch tired.

Thanks for filling the issue, but there's nothing to be done on nodemon's side.
