### ISSUE TITLE
Nodemon is unable to restart server on file change.

### ISSUE THREAD

**Issue by Anonsatyam** [remy/nodemon#1707]
- `nodemon -v`:2.3.0
- `node -v`:12.16.1
- Operating system/terminal environment:  Windows 10/ VS Code
- Using Docker? What image:  No
- Command you ran: npm start

### Expected behavior
After running the command **npm start** it was expected that whenever I change something in files and save, nodemon expected to restart my server automatically.

### Actual behavior
But after running the command **npm start**  it says [nodemon]: restarting due to changes... and it won't restart the server. Instead of that nodemon freeze.

![Nodemon_Issue](https://user-images.githubusercontent.com/33719556/79960247-ce5d2280-84a2-11ea-8714-be2c260d6bc2.jpg)

---

If applicable, please append the `--dump` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens**.

**Comment by Anonsatyam** [comment]
@remy Can you help, please?

**Comment by remy** [comment]
Have you tried running it outside of vscode? What does a pared down version of index.js look like? My guess is that, maybe, your code is trapping the kill signal…?

You can also add the env value of DEBUG=nodemon:* and it'll give you a blow by blow account of what's happening.

**Comment by Olluco** [comment]
Guys I am creating a server for the first time supported in node.js but I am having trouble with automatic code update in the 'JavaScript' file. The changes I make to 'index.ts' are not reflected in 'index.js' and when I run 'nodemon' it gets stuck in the line of code "[nodemon] restarting due to changes ...". Could someone help me solve this problem?

![Nodemon Mistake](https://user-images.githubusercontent.com/66092729/83202294-e9a7f700-a10c-11ea-839f-0c5e93754067.jpg)

In one terminal I am running 'npm run build' and in another terminal 'npm run dev'. Both are dependencies generated in the 'package.json'. Below is the code for 'package.json':

![package json](https://user-images.githubusercontent.com/66092729/83202337-fdebf400-a10c-11ea-9b2c-b15b23eebf44.jpg)

Finally I show you the code of 'index.ts':

![index ts](https://user-images.githubusercontent.com/66092729/83202082-72726300-a10c-11ea-9c48-3df76c5c5fe4.jpg)
