### ISSUE TITLE
Nodemon throwing error on run

### ISSUE THREAD

**Issue by VinayVini** [remy/nodemon#1709]
HI,

I have installed the nodemon on my system and when I tried to run the nodemon command I'm getting below error always, Attached screenshot below for reference.

- `nodemon -v`: Throwing same error as the screenshot on running nodemon -v
- `node -v`: v8.1.2
- Operating system/terminal environment:  Window 7
- Using Docker? What image: What is this?
- Command you ran: nodemon fileName.js

![Nodemon](https://user-images.githubusercontent.com/26251990/80278341-1da98a00-8713-11ea-806e-b6e5ee39ffa9.jpg)

**Comment by remy** [comment]
Can you run and return the result of `npm ls chokidar`

**Comment by VinayVini** [comment]
> npm ls chokidar

Hi Remy,
After running the above command `npm ls chokidar` in the VScode terminal/ windows command prompt got this error attached below screen capture.

![npm ls chokidar](https://user-images.githubusercontent.com/26251990/80307040-54030a00-87e4-11ea-8c5b-01e15afba199.jpg)

**Comment by remy** [comment]
Sod, I expect you're running nodemon from a global install. Not sure how
you check globally installed packages…

**Comment by remy** [comment]
I've found the reason why it's failing - you're on an unsupported version of node 8. Node 8 is up to 8.17.x - so you're missing a boat load of patches (security patches included).

Specific to what you're seeing is that the spread operator `...` landed in node 8.3.x and since you're on 8.1.x it's failing. Nodemon does support node 8, but chokidar is where the issue is throwing.

I can only (strongly) recommend you upgrade your node version, certainly within the major 8 version, and if possible higher as node 8 isn't [even supported](https://nodejs.org/en/about/releases/).
