### ISSUE TITLE
Graceful restart not working on windows

### ISSUE THREAD

**Issue by joshxyzhimself** [remy/nodemon#1712]
- https://github.com/remy/nodemon/issues/1567

And why is there a stale bot closing unsolved issues here?

It's not like that bot reopens the issue once it gets referenced or someone comments. Useless as hell.

**Comment by remy** [comment]
Stalebot closes issues that become inactive usually due to no pr or solutions proposed.

The issue you raised include no details on how to explicate (so I wouldn't be surprised if it didn't go the same way).

If you want someone to help you fix a problem you're seeing, make sure you include information (as per the issue template).
