### ISSUE TITLE
doc for execArgs

### ISSUE THREAD

**Issue by simonppg** [remy/nodemon#1716]
Do you have some example about the use of [execArgs](https://github.com/remy/nodemon/issues/1045), I'm trying to use nodemon config file without a `--inspect-brk` configuration flag in "exec" option, and passing it trough npm script, but I can't figure it out how to do it.

nodemon.json
```
{
  "watch": ["src"],
  "ext": "js,json,ts",
  "exec": "node -r ts-node/register src/index.ts",
  "env": {
    "NODE_ENV": "development"
  },
  "restartable": "rs",
  "ignore": [".git", "node_modules/**/node_modules"],
  "verbose": true,
  "execMap": {
    "ts": "node --require ts-node/register"
  }
}
```

package.json
```
"scripts": {
  "dev": "nodemon",
  "dev:debug": "nodemon --inspect-brk"
}
```
This is what I see when run the script
```
$ npm run dev:debug

> test-app@1.0.0 dev:debug /home/user/test-app
> nodemon --inspect-brk

[nodemon] 2.0.2
[nodemon] reading config ./nodemon.json
[nodemon] to restart at any time, enter `rs`
[nodemon] or send SIGHUP to 18867 to restart
[nodemon] ignoring: ./.git/**/* node_modules/**/node_modules
[nodemon] watching dir(s): src/**/*
[nodemon] watching extensions: js,json,ts
[nodemon] starting `node -r ts-node/register src/index.ts --inspect-brk`
[nodemon] spawning
[nodemon] child pid: 18880
[nodemon] watching 403 files

```
It looks like the config flag is passed, but the debugger doesn't start
[nodemon] starting `node -r ts-node/register src/index.ts --inspect-brk`

It only work if I write it on nodemon.json file like this:
`  "exec": "node --inspect-brk -r ts-node/register src/index.ts",
`

Could somebody give me some clue?

**Comment by remy** [comment]
You can't do this on the command line - put simply: nodemon is running two commands that take arguments: the exec (node in this case) and the user script. 

So nodemon errs on the side of the user code and passes it to the script.

When the exec is node (bare) then there's hacks to attempt to pass known args to node, but this isn't the case for your code.

I'd be inclined to do something like this (though you'll need to experiment since I'm not a typescript user):

```
"nodemon:dev": "nodemon --exec 'node --inspect-brk --require ts-node/register'"
```
