### ISSUE TITLE
why not support reading online document in nodemon.io?

### ISSUE THREAD

**Issue by xgqfrms** [remy/nodemon#1760]
# why not support reading online document in nodemon.io?

> Read the full documentation

https://nodemon.io/

https://github.com/remy/nodemon#nodemon

### Expected behaviour

> online document

https://nodemon.io/docs/cli/config
https://nodemon.io/docs/arch

### Actual behaviour

> github files

https://github.com/remy/nodemon/blob/master/doc/cli/config.txt
https://github.com/remy/nodemon/blob/master/doc/arch.md

### Steps to reproduce

https://nodemon.io/docs

https://nodemon.io/docs/cli/config

https://nodemon.io/docs/arch

**Comment by remy** [comment]
The documentation *is* online (indeed you have the links). 

What you're asking is why don't I copy them and maintain them in two separate places for the sake of (I guess) branding?

Because, right now, I don't want to replicate the documentation and do the design work. Maybe one day, but all the docs *are* online which is good for now.
