### ISSUE TITLE
 Internal watch failed: EBUSY: resource busy or locked

### ISSUE THREAD

**Issue by DasdWaller** [remy/nodemon#1794]
- `nodemon -v`: 2.0.6
- `node -v`: 14.15.0 (im using the nvm for windows)
- Operating system: Windows 10 (10.0.19042)
- Terminal environment: Windows Teminal (new edition, no the old cmd)
- Using Docker? What image: No
- Command you ran: nodemon --ext js,twig

[nodemon] 2.0.6
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,twig
[nodemon] starting `node ./bin/www`
[nodemon] Internal watch failed: EBUSY: resource busy or locked, lstat 'C:\DumpStack.log.tmp'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! project-name@0.0.0 watch: `nodemon --ext js,twig`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the project-name@0.0.0 watch script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in: ...

### Steps to reproduce
npx express-generator --view twig
set watch on scripts with "nodemon --ext js,twig" value
run on terminal "npm run watch"

**Comment by remy** [comment]
I think you're running nodemon from the root of your drive - going by the fact that there's a locked file detected in your root.

Move to a working directory (and probably ignore the log files too).

**Comment by Serjaek** [comment]
Hi, I've the same problem. I keep my "study/dev/project" stuff inside a nested subdirectory under C, external to "C/Users/...".
If I try to run nodemon inside a express.js project there, I get the following:
"[nodemon] 2.0.7
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node server.js`
[nodemon] Internal watch failed: EBUSY: resource busy or locked, lstat 'C:\DumpStack.log.tmp'  "

Otherwise, If I copy this project folder on my Desktop it works.
How can I resolve this? I want to keep these kind of projects there

**Comment by yogski** [comment]
I encountered similar problem on Windows 10. I managed to resolve it by adding `nodemon.json` config.
```
{
  "watch": ["./**"],
  "ext": "js"
}
```

The important point is adding dot (`.`) before path to tell nodemon to work in current directory.
