### ISSUE TITLE
Leading $ in filename fails to locate file.

### ISSUE THREAD

**Issue by Rob-pw** [remy/nodemon#1846]
- `nodemon -v`: 2.0.7
- `node -v`: v15.11.0
- Operating system/terminal environment: Lubuntu
- Using Docker? What image: N/a
- Command you ran: (Specified below)

### Expected behaviour
`nodemon "$myFile.js"` -> `[nodemon] starting 'node $myFile.js'`
Should run the filename specified.

### Actual behaviour
`nodemon "$myFile.js"` -> `[nodemon] starting 'node .js'`
Trims all but the extension and fails to locate the file.

### Steps to reproduce
Create a file with a leading $ (dollar sign) and attempt to run it. I assume it's incorrectly identifying it as a regex expression?

**Comment by Rob-pw** [comment]
This is actually much more pervasive, a `$` sign anywhere in the entry file filename causes the rest of the filename after that to disappear up until the following `.`, e.g., `x_$foo.js` becomes `x_.js`.

**Comment by harshithl1777** [comment]
Seems to be an issue with Node as well, not just nodemon. 

> This is actually much more pervasive, a `$` sign anywhere in the entry file filename causes the rest of the filename after that to disappear up until the following `.`, e.g., `x_$foo.js` becomes `x_.js`.

If you try running `node <example file with $>` you'll likely get an error since, as you said Node just cuts out all characters from the `$` until the dot. I've created an issue (nodejs/node#38053) in the Node repository explaining the problem. 

Thanks.

**Comment by harshithl1777** [comment]
It seems that the issue is not Nodemon or Node, but just the shell itself. The issue is now closed but if you check it out at nodejs/node#38053, according to @devsnek the shell is trying to recognize this is an environment variable, which is why it skips until the next `.`. I suppose the solution is just not to use `$` in filenames.

**Comment by RaisinTen** [comment]
Consider escaping the `$` by prepending it with a `\` like `nodemon \$myFile.js`.

**Comment by remy** [comment]
Like @RaisinTen said, you need to escape your `$` string - it's because your shell environment is trying to replace it with an environment variable. Similarly to how I might write `echo "Hello $USER"` it will swap `$USER` for my currently logged in user.

As it was noted, this isn't an issue with nodemon, and it might be wise to avoid using `$` in filenames in general as it'll bite you elsewhere down the chain.
