### ISSUE TITLE
Nodemon Issue

### ISSUE THREAD

**Issue by DiscordJaiiime** [remy/nodemon#1932]
- Versions: 
- `nodemon -v`: 2.0.12 and 2.0.13
- Operating system/terminal environment (powershell, gitshell, etc): CMD
- Using Docker? What image: no docker
- Command you ran: rs

### Expected behaviour

it restarts the program
### Actual behaviour

the window freezes until i press the x button to try to close the program

### Steps to reproduce

I'm unsure on how to reproduce this unfortunately but if I could call someone and show them that would be great. My discord is Jaiiime# 0001

----

If applicable, please append the `--dump` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens**.
![image](https://user-images.githubusercontent.com/86162936/136707902-7db45402-412a-4daf-891e-0ea567c513ea.png)

**Comment by DiscordJaiiime** [comment]
Yea but restarts don’t

**Comment by immortalmind2016** [comment]
nodemon --dump and upload the output

**Comment by abhi972527** [comment]
PS C:\Users\Abhijeet\Desktop\masai assignment\unit4\coding\17.11> nodemon app.js
nodemon : File C:\Users\Abhijeet\AppData\Roaming\npm\nodemon.ps1 cannot be loaded 
because running scripts is disabled on this system. For more information, see 
about_Execution_Policies at https:/go.microsoft.com/fwlink/?LinkID=135170.
At line:1 char:1
+ nodemon app.js
+ ~~~~~~~
    + CategoryInfo          : SecurityError: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess





What is this error
