### ISSUE TITLE
Security vulnerability - ansi-regex@4.1.0

### ISSUE THREAD

**Issue by GiovanniMoscati** [remy/nodemon#1953]
- nodemon versions: 2.0.14

### Description

Security vulnerability - ansi-regex@5.0.0

### Solution

Bump the package to >=5.0.1 version

**Comment by remy** [comment]
Good lord. Please update your own dependencies before filing these kinds of reports. *Your* deps are out of date.

I know I sound annoyed and it's because I get a lot of these issues where people don't bother actually checking that their own deps are out of date or not.

It's an easy test to do locally or to validate if you don't want to bump your own deps, you can check with snyk online: https://snyk.io/test/npm/nodemon?tab=dependencies

**Comment by GiovanniMoscati** [comment]
Hi Remy,

I got the name of the issue wrong, the package version of the ansi-regex was 5.0.0 (as in the description).
This is the description of the audit:

![image](https://user-images.githubusercontent.com/62437091/140931569-6834ccb1-0229-4907-a839-36f9eecb2a72.png)

I've nodemon@2.0.14

Am I doing something wrong?
If so, let me know, and I apologise for the waste of time of course!

**Comment by remy** [comment]
So, assuming nodemon is installed in your local package directory do the following:

1. `rm -rf node_modules` to completely clean your deps
2. `npm install`
3. `npm ls ansi-regex`

You should find you have 5.0.1

**Comment by GiovanniMoscati** [comment]
It was the yarn.lock, I've just deleted it and launched `yarn install` again and now I find the 5.0.1!

Thanks for your help Remy, have a good day!
