### ISSUE TITLE
nodemon keep first process running "Ubuntu 20.04"

### ISSUE THREAD

**Issue by pykeras** [remy/nodemon#1965]
Hi

nodemon can't stop the server properly ( for any type of Express app, all scripts )

- `OS`: ubutnu 20.04
- `node version`: v14.18.2
- `npm version`: 6.14.15
- `nodemon -v`:  2.0.15  --> installed as dev dependencies
- `command`: nodemon server.js

**on save** :
```
events.js:377
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (net.js:1331:16)
    at listenInCluster (net.js:1379:12)
    at Server.listen (net.js:1465:7)
    at Function.listen (<PATH>/node_modules/express/lib/application.js:618:24)
    at <MyCodePATH>/server.js:24:9 --> app.listen()
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
Emitted 'error' event on Server instance at:
    at emitErrorNT (net.js:1358:8)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  code: 'EADDRINUSE',
  errno: -98,
  syscall: 'listen',
  address: '::',
  port: 3000
}
```
  
  
**Current Solution (not the best approach but do the job)** : `sudo nodemon server.js`

**Comment by lpercivalDEV** [comment]
I am also having this same issue with a node/express app I am building. 

Nodemon crashes when I save the file I'm working in (despite not having any other errors).  Closing the terminal, stopping the server, restarting my editor/computer does not fix the issue.

I have to manually stop the process listening on my port each time by running `lsof -t -i:port` and then `sudo kill -9 PID` in order to run my server again. But the problem persists the next time I save in a file.

- OS: ubutnu 18.04.5
- node version: v14.15.3
- npm version: 8.3.0
-  yarn version: 1.21.1
- nodemon version: 2.0.15 
- command: yarn start

I get the same error as @pykeras above.
