### ISSUE TITLE
[BUG?] Stdin lost when nodemon restarts after a change

### ISSUE THREAD

**Issue by angelhdzmultimedia** [remy/nodemon#2022]
- `nodemon -v`: ^2.0.16
- `node -v`: 18.1.0
- Operating system/terminal environment: Windows 10 Home 10.0.19043 Build 19043

- Using Docker? What image: 
- Command you ran:

### Expected behaviour
Being able to run `npm run dev` to execute `nodemon -I --exec node --no-warnings --experimental-specifier-resolution=node --loader ts-node/esm ./src/main.ts` and being able to use the keyboard to navigate through `inquirer` list options, after a change in the code forces nodemon to restart.

### Actual behaviour
The first time I run the script, I have stdin. When nodemon restarts after a change in the code, I lose stdin.

### Final words
I'm using that script to allow Top Level Await in a TypeScript Node project but I don't think that's what's causing the issue. 

---

If applicable, please append the `--dump` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens**.

**Comment by angelhdzmultimedia** [comment]
Nothing? 

I was making a CLI with inquirer, and when nodemon restarted when there was a change in the code of a file, the inquirer keyboard keys didn't work to select the options. So I had to stop nodemon and restart manually...

**Comment by remy** [comment]
You didn't provide any code pared down or otherwise, so no, I suspect no one could help.

Either way, having used inquirer myself with nodemon, I know it's possible, but it's ropy as hell because inquirer needs stdin and moves the cursor around. In the end, I had to develop it without (it was the snyk cli back in 2016 or so)

**Comment by angelhdzmultimedia** [comment]
> You didn't provide any code pared down or otherwise, so no, I suspect no one could help.
> 
> Either way, having used inquirer myself with nodemon, I know it's possible, but it's ropy as hell because inquirer needs stdin and moves the cursor around. In the end, I had to develop it without (it was the snyk cli back in 2016 or so)

You started with "You didn't provide any code", and then you realized I couldn't provide any code, because the issue is specific to how nodemon do things, not that I'm the one doing something wrong as you implied.  The issue is present only when nodemon executes a script that has a process (inquirer in this case) that pauses execution to receive stdins. So by my clear explanation of the issue, a code or reproduction repo wasn't required.

I provide code and reproduction repos all the time, when I see it's necessary. 

I'm pretty sure the issue is not inquirer. It's nodemon  that fails to pass stdins to child processes after it does the "respawn" or "watch" magic.

Anyways, you just confirmed the issue and by your own attempt, you reached the conclusion that it's not gonna be fixed any time soon, so I will have to run projects in development that require inquirer without nodemon, and will have to stop and rerun node scripts each time (which works flawlessly but with a bit of more work). 

So someone could help after all. ;) 

Stay healthy, cheers.

**Comment by remy** [comment]
For anyone else following this: 

> So by my clear explanation of the issue, a code or reproduction repo wasn't required

No, this is rarely ever the case. That's why the issue template specifically asks for it. 

Providing a pared down example allows a dev to debug. The red flags in issues like this is the tall stack of requirements: stdin, enquirer, typescript, windows and the shell used (prompt, powershell, gitbash, etc). 

So yes folks, if you're expecting free support for the free tools (comments like "Nothing?" doesn't win any favours), then please do the bare minimum the original issue template asks.
