### ISSUE TITLE
nodemon not restarting automatically after i make changes in the index.js file

### ISSUE THREAD

**Issue by Sagar-Gondage** [remy/nodemon#2054]
Hi There,
if i run the command `nodemon run start` it works for the first time and i see the result at port number as well but
whenever i make changes in the index.js file server is not restarting automatically to see the changes i have to stop the nodemon and start it again every time.
terminal is stuck at  ->  [nodemon] restarting due to changes...

I have attached screenshot after making change in index.js also terminal which contains command, package.json file, index.js file and folder structure as well.

I tried to downgrade the version of nodemon as well but still facing the same issue.
OS that i am using is windows 11.
nodemon-verson -> 2.0.19

![image](https://user-images.githubusercontent.com/99082133/182525376-5a911f64-5edf-4b9d-ad8e-3b991085a775.png)

**Comment by remy** [comment]
That's an environment setting. Before you run nodemon, IIRC, windows requires you set the values like this: `set DEBUG='...'` (going by this post: https://www.shellhacks.com/windows-set-environment-variable-cmd-powershell/)

**Comment by Sagar-Gondage** [comment]
i have added the env variable
![image](https://user-images.githubusercontent.com/99082133/185077709-44666058-5efb-42d4-9615-9fb910aaf84e.png)
but i am still getting the same error in vscode terminal
![image](https://user-images.githubusercontent.com/99082133/185078315-1c071681-992f-4ee5-9f6e-da3c9d8bf812.png)

**Comment by remy** [comment]
This is what the debug output looks like:

![SCR-20220817-e2j](https://user-images.githubusercontent.com/13700/185080557-39c10316-37d4-412c-987a-c9ee504b5fc2.png)

You'll need to work out how to set the environment value in the terminal window you're using in VS Code. I can't really help you with VS Code support I'm afraid.

**Comment by Sagar-Gondage** [comment]
ok thank you!

**Comment by fredd2359** [comment]
Hello @remy hope you could help me out with this issue as well. Im having the same isue here and belive me that Ive seen a lot of the other issues here but can not get a solution.

**Currently I have:**
nodemon  global: 3.0.2
node: 20.10.0
npm global : 10.2.3
Windows 10
cmd terminal, powershell, and VSCode terminal doing the same.

**I've tried:**
- I have added the System32 to Path user variables and system variables
- Uninstalling and installing Node.js
- Uninstalling and installing nodemon even changing to older versions
- Deleted node_modules and runing npm install
- Restarted windows

Here are some captures wit the DEBUG setting

![image](https://github.com/remy/nodemon/assets/31856785/0a9b935a-a5f6-4160-9644-4bc10cb8734d)

It starts just good on port 5000 but when I do some chenges it does catch it but it gets stucked on the restart

Here is my code

![image](https://github.com/remy/nodemon/assets/31856785/6737db7f-037b-4ffb-902a-3c3366f97838)

![image](https://github.com/remy/nodemon/assets/31856785/4b96d5ff-9f8a-4b6c-8012-18cf79c57b8a)

I'm sure that the issue is not the nodemon library but maybe you have already figured what is causing this issue, thanks!

**Comment by Jahnavi-16** [comment]
Even I have the same isuue and I tried adding start in the script in package.json but its still showing the same error any ideas how to fix it ?
It was previiously working fine and Im not sure what caused this change ..

**Comment by Vaten0x** [comment]
It works after I changed these:

1. don't use powershell, use ubuntu or linux for it
2. npx nodemon -L server.js

**Comment by fasehdev** [comment]
Same thing happening to me right now.nodemon server not restart after i changes in code .  i install nodemon latest version nodemon@3.1.11  and i also create nodemon.json file to watch some specific files.   but issue not resolved

/// # @remy @Sagar-Gondage

**Comment by remy** [comment]
@fasehdev you're commenting on a stale issue that is extremely vague. I suggest creating a new issue and including details on how to replicate.
