### ISSUE TITLE
Curious to know the reasons behind casinos funding

### ISSUE THREAD

**Issue by agupta1989** [remy/nodemon#2067]
_**This isn't about a bug / issue.**_

Nodemon is great tool. While browsing through website, I came across the sponsors grid towards the bottom. 

![image](https://user-images.githubusercontent.com/3787965/193802863-cf0ea432-0bfd-4b35-9f16-1ddd826fc559.png)

Is it just a coincidence that nearly all of nodemon sponsors are from one common background / domain i.e. casino ?

Thanks !

**Comment by remy** [comment]
I'm pretty sure it's the fish following each other. I don't really have a better explanation, but they're inadvertently keeping me motivated :) (but I agree, it's definitely weird - I think socket.io and bunch others have a similar thing, not sure where it really comes from!)

**Comment by Kuravar** [comment]
Until I started actively gambling, I always had thoughts about why gambling remains relevant. Moreover, they are attracting an increasing number of players. Now I play in different online casinos, choosing them based on providers [https://casinosanalyzer.com/casino-software/pgsoft-gaming](https://casinosanalyzer.com/casino-software/pgsoft-gaming). I think this is popular because it is the easiest way to combine pleasant leisure time and benefits in the form of online earnings.

**Comment by JefinDX** [comment]
It is a SEO strategy from these companies. Featuring their website links in popular opensource project websites like nodemon will help to improve their ranking in search result.
