### ISSUE TITLE
Document differences and/or provide migration guide to Node.js native watch mode

### ISSUE THREAD

**Issue by trivikr** [remy/nodemon#2196]
### Is your request related to a problem? Please describe.

Thank you for developing and maintaining nodemon over the years.

Node.js added experimental watch mode in [v18.11.0](https://nodejs.org/en/blog/release/v18.11.0#notable-changes), and it was made stable in [v22.0.0](https://github.com/nodejs/node/pull/52074).

* As a new user of `nodemon` landing from blog posts, I want to know that a native option is available.
* As an existing user of `nodemon`, I want to check if I can migrate to native option.

### Describe the solution you'd like

* Provide a guide of migrating from `nodemon` to Node.js native watch mode
* Highlight differences between `nodemon` and Node.js native watch mode

### Describe alternatives you've considered

* Users may discover guides from community, for example:
  * https://www.jamesqquick.com/blog/using-node-watch-instead-of-nodemon/
  * https://medium.com/@moaidmoaidrazhy/node-watch-vs-nodemon-4c8f0fc8a1af
  * https://www.sitepoint.com/nodejs-live-restarts-nodemon-watch/
  * https://pawelgrzybek.com/til-node-v18-11-0-comes-with-a-watch-mode-so-you-might-not-need-nodemon/
* Request maintainers of Node.js native watch to write a guide.

### Additional context
- `nodemon -v`: N/A
- `node -v`: N/A
- Operating system/terminal environment: N/A
- Using Docker? What image: N/A
- Command you ran: N/A

**Comment by remy** [comment]
I get the sentiment, but what would motivate me to write detailed posted on how to migrate to a different thing? (there isn't).

Moreover, nodemon covers a vast number of uses cases way beyond the simple restart node process, again, I'm not inclined to write about all of those because they're fairly unlimited.

Perhaps at some point I might modify the readme to say "maybe you want `node --watch x`, but right now, at this point in time, I think it's redundant. 

I think what will eventually be needed is "why do you need to use nodemon over nodes native watch", but again, now isn't the time.

But feel free to write the things you've proposed, they sound like useful community posts.
