### ISSUE TITLE
[nodemon] unable to run executable: "npm" on Windows 8

### ISSUE THREAD

**Issue by PhilT** [remy/nodemon#389]
I'm trying to do something like:

```
"scripts": {
  "test-nodemon": "nodemon -w spec -e js -x \"npm -v\""
```

in my package.json. This works on Mac but I get an error on Windows. I'm running through git bash (I've tried cmd.exe and get the same error). I'm having trouble figuring out if it's on the path in that spawned environment. Obviously it's on the path of the parent process otherwise I wouldn't be able to run `npm run test-nodemon`.

Any ideas?

**Comment by jgoux** [comment]
Hello, I had the same issue using the last version of nodemon : 1.3.5.
By doing `npm install nodemon@dev` it installed the version 1.3.0-7 which worked. Why the fix isn't in 1.3.5 ?

**Comment by remy** [comment]
This is weird, because there's nothing that affects windows in the [diff between 1.3.0-7 and 1.3.x](https://github.com/remy/nodemon/compare/da96102889742f2cfdded49e73f33d60b33d153f). It only includes linux specific fixes (that were merged via a different branch).

Can someone put together a simple test that I can run in my windows environment (I'll try both cmd.exe and git bash). Equally, if anyone wants to take a crack at a PR, I'd be super grateful!

**Comment by jgoux** [comment]
@remy I'm sorry I'm on Ubuntu VM (on windows host). I didn't see an issue opened for this problem on Ubuntu so I posted there. :p 
But it does work with 1.3.0-7 and not in 1.3.5.

**Comment by remy** [comment]
@jgoux can you open a new issue then with details of the problem you're seeing?

**Comment by remy** [comment]
@jgoux in addition, I've just merged master into the code that has 1.3.0-7, and you can see (in this test PR) that there's no changes (after I resolve a conflict): https://github.com/remy/nodemon/pull/488/files (note that I've deleted the PR, but you can see still the details).

**Comment by remy** [comment]
Can you try nodemon 1.3.6? I've rewritten the exec logic (::sigh:: again) based around a very similar bug which might solve it: #489

**Comment by petercm** [comment]
Just an FYI I also get this error with nodemon@1.3.6
And as others have noted it works if I use 1.3.0-7
