### ISSUE TITLE
restart on signal

### ISSUE THREAD

**Issue by iliakan** [remy/nodemon#393]
Can nodemon restart a process on signal?

Right now when I send SIGINT, process just dies and nodemon waits for file changes (I'd like to restart).

**Comment by joeytwiddle** [comment]
My use case is that the server crashed due to (conditions) which I was able to fix without needing to change any code.

nodemon was waiting for "file changes" before it would restart.  So now my choices are:

1. Change some code, save it, then undo the change, save it.  (Not ideal, but works.)
2. Stop nodemon and start it again.  (I didn't especially want to do this because nodemon was already nicely running in a tmux window by a startup script.)
3. Send a signal to nodemon to tell it to restart the server, e.g. `kill -USR1 $nodemon_pid`.  (This is what I would have liked to do.)

No biggie though. :)

**Comment by cr0cK** [comment]
Wanted too! I have the similar issue, but inside a Docker container...

**Comment by Industrial** [comment]
I have the same issue.

I have several services all using the same library which is file-synced into their directories and thus into the docker container by a docker compose volume.

Nodemon is running inside the container but not (always) picking up the changes.

I want to control programmatically when to restart the services, so I can do that after the files have synced.

**Comment by TylerRick** [comment]
I have the same need. Sometimes nodemon doesn't restart even when I thought the file changed ... or we forgot to add a file to the list of files to watch for changes ... or we just want to restart a service manually for other reasons.

And since nodemon is usually what restarts our service for us, it seemed natural to expect it to be manually restartable too! 

In fact, it even shows this message on start up:
```
[nodemon] to restart at any time, enter `rs`
```

Except I can't seem to figure out how to attach to the process to enter `rs. (I'm running it in a container here too.)

I'd like to be able to restart it with `kill -HUP $nodemon_pid`.

**Comment by popey456963** [comment]
Unrelated to this issue, but if you wish to enter `rs` within a container, you'll need to start it up in interactive mode (`--interactive` or `-i`).
