### ISSUE TITLE
nodemon restarts when server is doing exit cleanup

### ISSUE THREAD

**Issue by bbung24** [remy/nodemon#519]
In my node server, I have some clean up to do before the server exits. The cleanup takes some time to do the clean up. When I save a file, nodemon sends the correct signal but restarts right after sending signal and before the clean up is finished. Below is the code that I used to handle the exit signal for nodemon. Am I doing something wrong here? 

``` javascript
process.once('SIGUSR2', function () {
  console.log('nodemon exit');
    cleanup(function(err) {
        process.kill(process.pid, 'SIGUSR2');
    });
});
```

**Comment by jmls** [comment]
did you ever get a solution to this ? I am hitting the same problem

**Comment by bbung24** [comment]
Nope. I'm just not using nodemon for my development right now..

**Comment by bbung24** [comment]
Actually I think they updated their code to do clean exit. I just added little bit of delay to it and it seems to work fine now.

**Comment by djabraham** [comment]
The delay switch seems to only debounce file change detection, when used like this:

    nodemon --delay 3500ms server.js

I have a readiness monitor running on a port that kubernetes checks for status updates. I need to delay shutdown for a couple of seconds so that status can be advertised on this port. I can catch the shutdown signal and start the graceful shutdown process, but nodemon immediately launches the service again and port listening conflicts occur ```EADDRINUSE```.

It would be great if there were a way to effect a truly graceful shutdown. At this point, anything short of killing any listening process will result in a port conflict.
