### ISSUE TITLE
Make the kill signal configurable

### ISSUE THREAD

**Issue by stelcheck** [remy/nodemon#521]
Namely:

https://github.com/remy/nodemon/blob/dd6ad0d879a1520554410cd662fac982c06f4c7c/lib/monitor/run.js#L195

I see there has been some windows-related issues, but I happen to be using a framework which uses SIGUSR2 for something else. As a matter of fact, if I use the https://github.com/bnoordhuis/node-heapdump module, nodemon will simply trigger heap dumps to be produced.

In my case at least, I'd like to be able to use nodemon.json to tell nodemon to SIGTERM instead of SIGUSR2. Any reasons why this would not be desirable?

**Comment by str1ke** [comment]
Same problem for me. Instead restarting app it takes heap dump :)

**Comment by Pchelolo** [comment]
+1

**Comment by remy** [comment]
I'll take a PR to make this configurable from the `nodemon.json`. You need to be super careful though because SIGTERM isn't always preventable, SIGUSR1 is used for node debugging (and god knows what else), and there's very little else to chose from. I think it's doable, but maybe you'll be catering for an edge case (which is okay, just saying).

**Comment by rosshadden** [comment]
:+1:
