### ISSUE TITLE
nodemon crash on production with no stack trace

### ISSUE THREAD

**Issue by NetanelBasal** [remy/nodemon#528]
I run my server on production for days all works fine, but for some reason it crash and restart again and i does not get anything from the log error, not stack trace, nothing.

```javascript
process.on('uncaughtException', function (err) {
  console.log('Caught exception: ' + err);
});
```

Can you suggest better way to debug the problem when nodemon restart please?

**Comment by remy** [comment]
I wouldn't catch the exception. In fact, [don't use it](https://nodejs.org/api/process.html#process_event_uncaughtexception). 

nodemon will push the error out to stderr. Try to replicate offline so you can see it and add more detail here.

But additionally, nodemon is a development tool, I wouldn't typically recommend using it for production. You're safer with something like PM2 I think (because nodemon will stay down when it crashes, whereas production, you usually want it to stay *up*).
