### ISSUE TITLE
Can't watch all files in a directory

### ISSUE THREAD

**Issue by daveroberts** [remy/nodemon#743]
Nodemon can't watch all files for change in a directory.  It looks like others are trying to pass --ext '.' for this, but that throws an exception.

```
/apps/home/daver/code/npm-scripts-example/node_modules/nodemon/lib/config/exec.js:158
  extension = extension.match(/\w+/g).join(',');
                                     ^

TypeError: Cannot read property 'join' of null
    at exec (/apps/home/daver/code/npm-scripts-example/node_modules/nodemon/lib/config/exec.js:158:38)
    at /apps/home/daver/code/npm-scripts-example/node_modules/nodemon/lib/config/load.js:56:29
    at callback (/apps/home/daver/code/npm-scripts-example/node_modules/nodemon/lib/config/load.js:161:5)
    at ReadFileContext.callback (/apps/home/daver/code/npm-scripts-example/node_modules/nodemon/lib/config/load.js:171:14)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:303:13)
```

**Comment by nikdo** [comment]
I was also watching all files with nodemon, but I'm not sure if it is supported use case as it is not mentioned anywhere except some blogposts.

`--ext '.'` stopped working with #693.

If you still want it, the only workaround I have found is to stick with version 1.7.2.

**Comment by musichen** [comment]
The same thing is here:
[nodemon] watching: *.*
[nodemon] starting `node --stack_size=4096 app.js`
/home/username/dev/bitbucket/myproject/node_modules/nodemon/lib/config/exec.js:158
  extension = extension.match(/\w+/g).join(',');
                                     ^
TypeError: Cannot read property 'join' of null

**Comment by daveroberts** [comment]
This still looks to be the case.  I tried again with v1.12.5

**Comment by dominykas** [comment]
Seems to be fixed in v1.13.3 - I ran with `--ext '.'`. nodemon restarted with updating `README.md` and `index.js`.

**Comment by dominykas** [comment]
It still won't restart on extension-less files, e.g. `README` - not sure if that's something `nodemon` needs to support?

**Comment by remy** [comment]
Shouldn't the "all" ext be `*` not `.` and then that matching rule updated for a special case? That said, it's straight forward to support both of these "special" rules in `match.js`

**Comment by dominykas** [comment]
It does currently work with with both (`*` and `.`), but only if the file has an extension. However that is due to a side-effect, I think: https://github.com/remy/nodemon/blob/master/lib/config/exec.js#L177-L184. This code essentially removes any `*` (why? all tests still pass if I remove) characters, and then strips the leading `.`, which essentially makes `ext` an empty string.

Because it currently works with `--ext '*'` and `--ext '.'`, I'm thinking there's no harm to keep this behavior. I also think it's worth supporting `--ext ''`, because that's what `*` and `.` become internally anyways.

Getting the code for above is, indeed, straightforward - mostly because the code is already there, just needs some tests to lock it in.

Matching extension-less files is a little more interesting. By default, `nodemon` watches for changes in `*.*` - which means an extension is required. I'm thinking I could just replace that `*` and be done with it... but I wonder if `*.*` was used deliberately? There are some other exceptions related to `*.*`, that would probably need support for `*`.

**Comment by remy** [comment]
Live in nodemon@1.14.0
