### ISSUE TITLE
Not passing arguments when using default file

### ISSUE THREAD

**Issue by pensierinmusica** [remy/nodemon#750]
Hi,

I just noticed that `nodemon` seems to not pass arguments when when it executes default files.

This works as expected:

```
nodemon index.js --log
```

This still executes `index.js` but doesn't pass the arguments along:

```
nodemon --log
```

Any idea why is this?

Thanks!

**Comment by remy** [comment]
hmm, not sure, but can you try `nodemon index.js -- --log`?

**Comment by pensierinmusica** [comment]
Ok, I tried it, `nodemon index.js -- --log` passes the arguments along to `index.js`.

On the other hand, `nodemon --log` executes `index.js` but doesn't pass arguments along.

Any idea?

**Comment by pensierinmusica** [comment]
@remy, ok I've found what is causing the problem.

When using default files, `nodemon` needs to move the arguments after the file.

Let me try to exemplify this with code.

#### 1. Correct
```sh
nodemon

# executes -> "node index.js"
```

#### 2. Correct
```sh
nodemon index.js  --log

# executes -> "node index.js --log"
```

#### 3. Wrong
```sh
nodemon --log

# executes -> "node --log index.js"
```

So the only problem is with case number 3. We need to make sure arguments are passed to `node` **after** the executable file.

Do you have a sec to fix this, or would you prefer me to look into it?

Thx, cheers!

**Comment by pensierinmusica** [comment]
@remy any update on this?

**Comment by remy** [comment]
Sorry, no, but now that I've given it some thought, there's a bit of a problem. Should `nodemon --log` put the run:

1. `node --log .`
2. `node . --log`

The `.` being detected by nodemon. Because if it's the 2nd one, how about `nodemon --inspect` - where should that go?

That's to say: it's really not clear where it should go and nodemon has to just make a decision itself. A long time ago, I decided that arguments would be passed to the `exec` process. However, I can see that perhaps `nodemon -- --log` should pass the `--log` to the script.

Agree? If so, it's a (potentially breaking) change that's required to put all non-slurped arguments after the script. Let me know what you think and if you're in agreement, wanna take a shot at the PR?

**Comment by pensierinmusica** [comment]
@remy sounds good to me:

> all non-slurped arguments after the script

Unfortunately a bit overwhelmed at the moment for a pr...

**Comment by remy** [comment]
@pensierinmusica got a PR on the go. Reckon it's good too 👍 😄
