### ISSUE TITLE
shmget error, please try later.: No such file or directory

### ISSUE THREAD

**Issue by wxlfight** [remy/nodemon#754]
node version: 4.2.3
nodemon version: 1.8.1
mac version: osx Yosemite 10.10.5

what's the problem:
This problem seems happened when i upgrade node from v0.12 to v4.2.3, after that, when i update my app, then nodemon throw out this error: 'shmget error, please try later.: No such file or directory', but my app is still not change anything.
i still didn't got the key of the problem after searching in google. 

This is the console log:
$ nodemon app/index.js
[nodemon] 1.8.1
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node app/index.js`
Listening on http:8045

[nodemon] restarting due to changes...
shmget error, please try later.: No such file or directory
[nodemon] restarting due to changes...
shmget error, please try later.: No such file or directory

**Comment by sensoroDj** [comment]
I have the same problem. how to do?

**Comment by wxlfight** [comment]
@remy

**Comment by remy** [comment]
I've no idea. Did you reinstall/build nodemon since you changed node version?

**Comment by imsobear** [comment]
+1 for this problem, and i have reinstalled nodemon

**Comment by nodeman777** [comment]
+1 for this problem, Mac os

**Comment by remy** [comment]
This isn't directly related to nodemon, so far as I can tell. If a node version fixes, then I'd recommend that as @nodeman777 suggests.

Otherwise, googling shows this has to do with shared memory (and possibly the lack thereof?): https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man2/shmget.2.html

Closing with the recommendation of a node upgrade (to LTS).
