### ISSUE TITLE
Nodemon stuck at restarting

### ISSUE THREAD

**Issue by sarahsga** [remy/nodemon#813]
Nodemon detects file change, attempts to restart the server, but takes forever long to restart - stuck at restarting the server and the server never restarts unless stopped manually. 

Infact, whenever I Ctrl+s save a file WITHOUT making any changes, the message appears "restarting due to changes...", and stays there, never restarts. Please help

Also, when I enter rs, nothing happens.
Also, it never states "listening on port 3000", but the page responds in browser. (Following is the cmd snapshot):

![nodemon](https://cloud.githubusercontent.com/assets/10798986/14293686/1542da40-fb87-11e5-98c8-d176bff68a8f.PNG)

OS: Windows 10
Node version 4.4.2
npm version 2.15.0
nodemon version 1.9.1

**Comment by cmswalker** [comment]
Same issue just wanted to give my 2 cents(workaround below)
uninstalling and reinstalling fsevents seems to work for many people running node >= v5

I've been using node 4.4.3 for a while and just upgraded to El Capitan. Seems to be a race condition with the way OSX files are being watched through nodemon -> chokidar -> fsevents.  Also experienced this with a later version of Yosemite.  Would get infinite restarts as many of these other issues have stated until i reinstalled/rebuilt chokidar with a lower version of itself and fsevents.

Then, i would still have the issue in my production app due to a frontend .js file that we build on app startup/save (we concatenate everything into one file for the client via node fs vs. using a task runner or webpack, etc.)  

So I ran nodemon with --verbose and sure enough, the race condition would still persist with fsevents and chokidar rebuilt/downversioned, so the only workaround was to either add these implicitly to the nodemon --ignore list, or to run the app with -C (on-change-only) preventing a file-change restart on app boot and persisting nodemon to reboot/watch on actual changes to file vs. startup.

Going to look into this more for older node version users, but wanted to give my 2 cents for those still struggling after rebuilding fsevents/chokidar.

**Comment by sberserker** [comment]
Have the same issue on Windows 10
nodemon version: 1.10.2
node version: 6.6.0
npm version 3.10.3
<img src="https://cloud.githubusercontent.com/assets/1973441/18813143/91b88cda-82a2-11e6-91e3-e42e1676d860.png" width="400px">

**Comment by sberserker** [comment]
Had exact same issue, installing updates and restarting my laptop solved it.

**Comment by simpss** [comment]
I can reproduce it with nodemon `1.12.5`
```
$ node --version
v6.12.0
$ npm --version
3.10.10
```

As you can see from the logs, it starts up fine, then does my normal setup and logs some line to show that it's started up. I then make a change and nodemon says it's restarting, but it actually doesn't restart, the app still responds. If I make another change after a couple seconds, again nodemon says it's restarting, but actually isn't.

```
[nodemon] 1.12.5
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `ts-node ./src/index.ts`
Setting up server on port: 3002
Server started
[nodemon] restarting due to changes...
[nodemon] restarting due to changes...
```
I also created a small test to make sure nodemon really doesn't make the restart happen.
```
[nodemon] 1.12.5
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `ts-node ./src/index.ts`
Setting up server on port: 3002
Server started
Been Running for 0 seconds
Been Running for 1 seconds
Been Running for 2 seconds
Been Running for 3 seconds
Been Running for 4 seconds
Been Running for 5 seconds
[nodemon] restarting due to changes...
Been Running for 6 seconds
Been Running for 7 seconds
Been Running for 8 seconds
Been Running for 9 seconds
Been Running for 10 seconds
Been Running for 11 seconds
[nodemon] restarting due to changes...
Been Running for 12 seconds
Been Running for 13 seconds
Been Running for 14 seconds
Been Running for 15 seconds
```
So nodemon obviously understands that the files have changed, but it doesn't restart the process properly.

If there's any info I can give to help reproduce this, I'm happy to answer any questions.

**Comment by remy** [comment]
This is great, thank you. I'm not familiar with typescript, and if you can
provide a gist (or repo if necessary) with the `src/index.ts` and
typescript version you're running so I can replicate locally, I can try to
debug to see why it's lingering.

Also, what OS are you running?

**Comment by simpss** [comment]
I'm on Debian Stretch (9)
I've made a simplified sample that shows the issue here: https://github.com/simpss/nodemon-issue-813-repro

Some instructions are included in the readme. If you have any questions, let me know.

**Comment by remy** [comment]
@simpss thanks for this. Do you have any tips on how I can develop against this too - or just hack directly inside the node_modules directory? (sorry, I always find the docker dev process a little tricky)

**Comment by simpss** [comment]
I've added `start-mounted.sh` as an example.  
If you open it up, you'll see there's a `--mount` parameter with options `source` and `target`. You can mount any host directory to the container. 
So to pass a host `src` dir to the container you'd do:  
```
--mount type=bind,source=/full/host/path/to/packages/package/src,target=/opt/packages/package/src
```
and to have a host `node_modules/nodemon` directory inside the container you can do:  
```
--mount type=bind,source=/full/host/path/to/packages/package/node_modules/nodemon,target=/opt/packages/package/node_modules/nodemon
```

**Comment by remy** [comment]
@simpss I've been testing this out more and I'm pretty certain the issue is between nodemon the Docker build (`debian:stretch`) and the [kill command found here](https://github.com/remy/nodemon/blob/14fcf944042600d18974ebe911ae26fef09a2238/lib/monitor/run.js#L306)

I don't really know enough about what goes on under the hood with processes and kill signals, but I need to add a local change that will echo out that the kill command ran the callback, but I'm 90% sure it's failing.

---

I've just run another test, and when the Dockerfile includes `procps` in the `apt-get install` the restart works.

**Comment by simpss** [comment]
As I understand, It's failing because `kill` command doesn't exist on the minimal system and can be worked around by installing `procps`. 

From my point of view if there's no way to kill a process without the `kill` command. It would be enough to handle the failure and just log it out as a warning. 

Something like: "'kill: command not found', so you have procps installed?"

**Comment by remy** [comment]
I've dug a lot deeper and found the root cause now.

It's basically this: https://nodejs.org/dist/latest-v8.x/docs/api/child_process.html#child_process_subprocess_kill_signal (read from "Also note: on Linux").

I've got a working solution that I'm merging into nodemon right now: https://github.com/remy/pstree

**Comment by benjoun** [comment]
Hi!

I do have the same issue, with windows 10, when I make a change it says "restarting ..." but doesn't restart the server, see snapshot

![nodemon](https://user-images.githubusercontent.com/13507406/36079036-e8af2bb0-0f7e-11e8-9a48-1738ca6e038f.jpg)

**Comment by tynorr** [comment]
Hi Ramy!
Nodemon still cannot start automatically. 

- [nodemon] 1.17.1
- [nodemon] to restart at any time, enter `rs`
- [nodemon] watching: *.*
- [nodemon] starting `node app.js`
- Slm Blue, server tarafından dinlenilen port : 3000
- [nodemon] restarting due to changes...

`

**Comment by remy** [comment]
You'll need to raise a new issue if you're experiencing problems (as this original issue was raised 48 months ago and the code has long changed).

**Comment by rahulsanju** [comment]
I'm also having the same issue with windows 7 and nodemon 1.17.3

**Comment by LuckStock** [comment]
Started to have this issue recently on Windows 10 platform.
Uninstalling and re-Installing the latest nodemon doesn't help.
Running nodemon in legacy mode helps, but better to have a native fix.

`> nodemon -v
1.17.5`

`> node -v
v8.11.2`

`> npm -v
6.0.1`

**Comment by slaterbbx** [comment]
Same issue here, driving me crazy, just started out of no where.. Not specific to any project, just the environment. I think it started after some environment path variable changes, is this possible?

**Comment by ningacoding** [comment]
Why this closed? problem persists on last version: 1.18.10

**Comment by maykbrito** [comment]
I was using a Windows 7 and had this problem.

After looking at the environment variables, I notice that was missing some.

To force it (maybe you don't need all of this) I place this variables there

```txt
C:\Windows;C:\Windows\system32;C:\Windows\System32\Wbem;
```

**Comment by chucklu** [comment]
Same problem with ndoemon 2.0.6, I have to press enter button on keyboard , then it will continue to restart.

**Comment by mrashidtufail** [comment]
tech details

windows 10
node 16+
npm 8+
nodemon 2+

i am also facing the same issue nodemon got stuck on restart, to resolve this
i just added C:\Windows\System32 in my environmental variable PATH then restart vs code and it's working fine
