### ISSUE TITLE
Just requiring nodemon borks ctrl+c 

### ISSUE THREAD

**Issue by joshhunt** [remy/nodemon#816]
I noticed that merely requiring nodemon captures SIGINT and requires two ctrl+c exits to quit the script.

This test case reproduces with latest 1.9.1:

``` javascript
require('nodemon'); // comment this out and observe that the bug no longer occurs
setInterval(function () {}, 1000);
```

I fiddled around with nodemon and found out that removing [these three lines](https://github.com/remy/nodemon/blob/6ccb29/lib/monitor/run.js#L345-L347) 'fixed' the problem, however I'm sure this isnt the right way to fix this.

**Comment by mnquintana** [comment]
Still running into this in 1.9.2 too – I'd be willing to work on a fix! 😄  But I'm not sure what the Right Way to do this is either. In the meantime I'm trying to find a reasonable workaround that doesn't involve forking nodemon.

**Comment by remy** [comment]
Worth adding some background: 

- What version of node?
- What OS (though I'm guessing you're both on non-windows based on the link to the potential change)?

I'll update to match what you're using to take a look too.

**Comment by mnquintana** [comment]
This has been with Node 5.8 and 5.11.0, and OS X 10.11.4. Let me know if there's any more information you need!

**Comment by vlkosinov** [comment]
@remy
The same problem in node v6.2.1, nodemon 1.9.2, OS X 10.11.4

**Comment by remy** [comment]
Can anyone investigate this?

**Comment by jmm** [comment]
@joshhunt Thanks for the pointer to those lines (and :+1: for using the permalink :smiley:).

@remy It seems to me that it's related to this:

> [Signal Events](https://github.com/nodejs/node/blob/180867d6a6edd5e2bf6729696177a31c6908b161/doc/api/process.md#signal-events)
> [...]
> It is important to take note of the following:
> [...]
> * `SIGTERM` and `SIGINT` have default handlers on non-Windows platforms that
  resets the terminal mode before exiting with code `128 + signal number`. If
  one of these signals has a listener installed, its default behavior will be
  removed (Node.js will no longer exit).

I don't understand the architecture of this library, or the intricacies of the underlying stuff, well enough to have a solid idea of the solution. Here are a couple of ideas though:

* If I move [this line](https://github.com/remy/nodemon/blob/be5d4e8d13a6dcc16c65b5bce59edef54496a8ae/lib/monitor/run.js#L307) out of the branch for `!config.required` to after the conditional, I get exit with a single <kbd>Ctrl+C</kbd> with the repro. Tests appear to pass. Like I said, I don't understand the architecture well enough to know if there's a reason for not doing that.

* If instead I change [this line](https://github.com/remy/nodemon/blob/be5d4e8d13a6dcc16c65b5bce59edef54496a8ae/lib/monitor/run.js#L346) as follows...

  ```diff
  - if (!utils.isWindows) {
  + if (!(utils.isWindows || utils.isRequired)) {
  ```

  ...I get exit with a single <kbd>Ctrl+C</kbd> with the repro. Tests appear to pass. Again, I don't know if that's skipping some important cleanup or is appropriate in general.

In the following examples I'm going to use `prompt$` to represent the prompt. In the first case, when I exit I get:

```
^Cprompt$
```

While in the second I get:

```
^C
prompt$
```

I'm guessing that's attributable to the:

> resets the terminal mode before exiting

In the first case the default `SIGINT` handler is still getting overwritten, so that's not happening.

**Comment by mnquintana** [comment]
Has this been fixed in any of the recent releases of nodemon? Couldn't find any references to this issue

**Comment by remy** [comment]
@mnquintana I didn't see a PR come through. If you're able to either put together a failing test case and/or a PR (ideally both), I'd be happy to review and merge.
