### ISSUE TITLE
Windows: file watching but nodemon doesn't restart the server.

### ISSUE THREAD

**Issue by roccomuso** [remy/nodemon#830]
My issue, might be related to #818
I'm under Windows 10.

I'm lauching my script in this way:

```
$ npm run development
```

and that's how my package.json rule is defined:

`"scripts":{
    "development": "./node_modules/.bin/nodemon -V --watch views server.js"
}`

Once executed and after having modified a file in the watched dir (views/), I have this on the console:

![cattura](https://cloud.githubusercontent.com/assets/6730217/15098936/c687c514-1549-11e6-95c2-3780d2623325.PNG)

I have 3 files in the directory, and index.html is the one being modified, but my server it's not going to be restarted.

**Comment by roccomuso** [comment]
Well,
now it seems to be working.
Actually it turned out that my views directory doesn't need a server restart to show me the changes.
How nodemon knows that?

**Comment by kenhoff** [comment]
I think that's expected behavior - I don't think that nodemon has anything to do with that. 

What happens is: 

The client (browser) requests `index.html`, and `server.js` grabs the `index.html` file and sends it back over the wire. You make a couple of changes to `index.html` in your text editor, and save them; `nodemon` doesn't restart because it's not watching the `.html` extension. The client requests `index.html` again, and again `server.js` grabs the `index.html` file (now it's the modified one) and sends it back over the wire.
