### ISSUE TITLE
Hey,guy I need restarted event 

### ISSUE THREAD

**Issue by huangyanxiong01** [remy/nodemon#840]
```js
/**
 * 刷新浏览器
 */
gulp.task('nodeMonRestartAndBrowserSyncReload', ['webpack'], function () {
   nodemon.on('restart',function () {
       console.info('app restart');
       browserSync.reload();
   })
});
```
Hey,guy I need  `restarted`  event when nodemon restart has been completed  trigger `restarted` event

**Comment by remy** [comment]
So... "hey, guy" isn't a great title for your issue, but I'll assume this is a language thing.

I've answered this before, but I'm pretty sure it's not in the FAQ (so I'll try to get around to getting this in too).

The reason why this event doesn't exist is because nodemon has no idea about what your code is doing. So it doesn't know when your server is read for a browserSync reload. You could be using express, or hapi or vanilla or something else, or not at all...

So, currently it's not possible.

**Comment by huangyanxiong01** [comment]
@remy thank you,The problem has been resolved,The answer from `gulp-nodenom` README
```
Some people want to use browser-sync. That's totally fine, just start browser sync in the same task as nodemon({}) and use gulp-nodemon's .on('start', function () {}) to trigger browser-sync. Don't use the .on('restart') event because it will fire before your app is up and running.
```

**Comment by remy** [comment]
Perfect.
