### ISSUE TITLE
nodemon restarting multiple times with Node v6.2

### ISSUE THREAD

**Issue by cbengtson85** [remy/nodemon#844]
I upgraded to Node v6 from v5 and now nodemon is restarting multiple times when a file changes.
I downgraded back to v5 and it is working as expected.  No other changes were done other than the node version changing.

**Comment by cbengtson85** [comment]
uninstalled fsevents and reinstalled, now working as expected.

**Comment by cmswalker** [comment]
Same issue just wanted to give my 2 cents(workaround below)
uninstalling and reinstalling fsevents seems to work for many people running node >= v5

I've been using node 4.4.3 for a while and just upgraded to El Capitan. Seems to be a race condition with the way OSX files are being watched through nodemon -> chokidar -> fsevents.  Also experienced this with a later version of Yosemite.  Would get infinite restarts as many of these other issues have stated until i reinstalled/rebuilt chokidar with a lower version of itself and fsevents.

Then, i would still have the issue in my production app due to a frontend .js file that we build on app startup/save (we concatenate everything into one file for the client via node fs vs. using a task runner or webpack, etc.)  

So I ran nodemon with --verbose and sure enough, the race condition would still persist with fsevents and chokidar rebuilt/downversioned, so the only workaround was to either add these implicitly to the nodemon --ignore list, or to run the app with -C (on-change-only) preventing a file-change restart on app boot and persisting nodemon to reboot/watch on actual changes to file vs. startup.

Going to look into this more for older node version users, but wanted to give my 2 cents for those still struggling after rebuilding fsevents/chokidar.
