### ISSUE TITLE
Changes to files in the root folder are not picked up

### ISSUE THREAD

**Issue by UltraVisual** [remy/nodemon#909]
Code in dependant modules trigger a restart of nodemon - but changes to anything in the root or src folders do not get picked up :(

```
nodemon({
        script: 'app.js',
        ext: 'js jsx',
        verbose: true,
        ignore: [
            'public',
            'test',
            'scripts',
            'config'
        ],
        watch: [
            '../common/lib',
            '../platform/lib',
            './'
        ].,
        env: { 'NODE_ENV': process.env.NODE_ENV || 'production' }
    })
```

maybe I am missing something - using the legacyWatch flags triggers this to work but we don't feel that polling is an efficient way of checking for changes.

**Comment by BrainBacon** [comment]
Just ran into this issue as well. I think it has something to do with the file matching and using `../` or `./` in front of any file in the `watch` array. I set up a very simple application to watch a single file. When I told Nodemon to watch `./index.js` it would not restart while it did restart while watching `index.js`.
The following is output from verbose mode in Nodemon when a restart does not happen:
```
[nodemon] files triggering change check: index.js
[nodemon] changes after filters (before/after): 1/0
```
A successful restart will have the following messages:
```
[nodemon] files triggering change check: index.js
[nodemon] matched rule: **/index.js
[nodemon] changes after filters (before/after): 1/1
```

`index.js`:
```js
var express = require('express');
var app = express();

app.get('/', function (req, res) {
    res.send('Hello World!');
});

app.listen(3000, function () {
    console.log('Example app listening on port 3000!');
});
```

`nodemon.json` (will fail to restart due to changes in `index.js`):
```json
{
  "verbose": true,
  "watch": "./index.js"
}
```

`nodemon.json` (will restart successfully due to changes in `index.js`):
```json
{
  "verbose": true,
  "watch": "index.js"
}
```

**Comment by UltraVisual** [comment]
Yeah I moved to node-dev instead as that seems a bit smarter and watches the imported files only :)

**Comment by remy** [comment]
@UltraVisual node-dev is clever in that it instruments the `require` statement, so it's watching what you're using in memory (I remember browsing the source a year or so ago).

**Comment by UltraVisual** [comment]
Yeah I thought it was quite a clever idea - fits my needs but I do like the configurability (is that a word?) of nodemon.

**Comment by BrainBacon** [comment]
@remy that does sound clever, but it wouldn't work for me. I'm using an IoC pattern via a [library I wrote](http://nodep.org). Therefore Nodemon's watch option is the best choice for me.
