### ISSUE TITLE
How did you add support for node arguments such as --inspect?

### ISSUE THREAD

**Issue by rainabba** [remy/nodemon#929]
I've been trying to get my npm "test" script to work with --inspect and I've found a workaround (lab doesn't support passing --inspect right now), but nodemon does quite nicely so I'm trying to understand the fundamental difference between the 2 to see if I can create a PR to add the functionality to lab.

When I run `npm test`, I understand that what's really happening is that my "test" script is run, which is "lab ...." and in reality, NPM is executing node_modules/.bin/lab.cmd which has the node command in it. It looks like the same is true for node-mon, and yet --inspect works which means that either it's injected somehow, or detected inside node-mon and enabled or another instance of node is started.

Any light you could shed on this would be greatly appreciated.

**Comment by remy** [comment]
I "eat" known arguments. All others are passed directly to node, which is
how new args automatically work.

**Comment by rainabba** [comment]
Thank you. Might you be willing to point me to the code where you're calling node and passing those other arguments? I think that might be the key.

Also, when i use `npm run-script dev` to start my "dev" script of `nodemon --inspect ./lib/index.js` (via package.json scripts that is), I'd expect that nodemon is already running in a node context. Are you effectively starting a child node process that gets "--inspect" in that case, or is that outer context somehow exited/quit before you start node?

**Comment by eeve** [comment]
how to set the port, eg: node --inspect=9229

**Comment by mayank-dunzo** [comment]
I run my node projects by passing `--use_strict` flag to node scripts instead of setting `use-strict` in each file. 
In production I tend to use pm2 and nodemon in dev environments.

I have set up the node scripts as such in my package.json:
```js
// package.json
{
  ...
  "scripts": {
    "start": "node --use_strict index.js",
    "dev": "nodemon --use_strict index.js"
  },
  ...
}
```
Whereas the `start` script runs just fine, with `use_strict` flag working correctly , I can't get the `dev` script to run in strict-mode. This is very important for parity to exist between my local, dev and prod environments. Is there a way i could pass the `--use_strict` flag to my node script whilst running it with nodemon?
