### ISSUE TITLE
only restart once

### ISSUE THREAD

**Issue by huangyanxiong01** [remy/nodemon#951]
nodemon --harmony -w app.js app.js
```
[nodemon] 1.11.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: app.js
[nodemon] starting `node --harmony --harmony app.js`
open http://127.0.0.1:3000
[nodemon] restarting due to changes...
[nodemon] starting `node --harmony --harmony app.js`
open http://127.0.0.1:3000

```

**Comment by mikehenrty** [comment]
Hi @huangyanxiong01, I'm having the same problem as you: when you watch a specific file, nodemon will only restart the app after the *first* file change. All changes made to the file after that don't trigger a restart.

I believe the problem is actually this bug with the `chokidar` package:
 https://github.com/paulmillr/chokidar/issues/237

(I assume from your avatar that you are using linux, which appears to be where this bug occurs). The workaround from that bug would be to run your app like this `nodemon --harmony -w '[a]pp.js' app.js`. Not ideal I know, but I don't think we will get a fix from `chokidar` any time soon.

Also could you change the name of this bug to `Watching file only restarts server after first change on Linux` or something more descriptive? Right now it's not clear what bug you are reporting.

**Comment by albertnetymk** [comment]
I still experience this problem with nodemon 2.0.2; my current workaround is to use `-L`. I tried `chokidar 3.3.0` directly, it seems to work fine.

**Comment by sinbino** [comment]
I have the exact same problem, also occurs with nodemon 3.0.1 as of July 2023. watch a single file, it only detects the first change.

**Comment by remy** [comment]
> I have the exact same problem, also occurs with nodemon 3.0.1 as of July 2023. watch a single file, it only detects the first change.

Can you raise a separate issue as what you're reporting is new. Can you also include pared down information on how to replicate
